import os
import re
import time
import json
import subprocess
import logging
import requests
from datetime import datetime
from pathlib import Path
from core.events import event_bus

logger = logging.getLogger(__name__)

class SystemUpdateService:
    _cached_info = None
    _cache_time = 0
    _CACHE_DURATION = 20  # seconds — fast propagation of updates
    _current_update_proc = None
    _update_start_time = 0

    @classmethod
    def get_version_info(cls, simulate=False, force=False):
        now = time.time()
        if not force and not simulate and cls._cached_info and (now - cls._cache_time < cls._CACHE_DURATION):
            return cls._cached_info

        base_dir = Path(__file__).resolve().parent.parent.parent
        now_formatted = datetime.now().strftime('%b %d, %Y, %I:%M %p')

        env = os.environ.copy()
        env['GIT_TERMINAL_PROMPT'] = '0'
        env['GCM_INTERACTIVE'] = 'never'
        env['GIT_ASKPASS'] = 'echo'

        info = {
            # Use empty string as unknown sentinel — never hardcode a stale commit.
            # If we cannot determine current_commit, we cannot reliably compare against
            # the latest remote commit, so update_available defaults to False.
            'current_commit': '',
            'current_author': 'WhatsQ',
            'current_date': now_formatted,
            'current_message': 'System is operating on the latest release',
            'latest_commit': '',
            'latest_message': 'System is up to date with origin/main',
            'latest_author': 'WhatsQ Team',
            'latest_date': now_formatted,
            'last_updated': now_formatted,
            'last_checked': now_formatted,
            'update_available': False,
            'is_git': True,
        }

        # 0. Load cached release metadata file if generated by deploy.sh
        meta_candidates = [
            base_dir / 'backend' / 'version_meta.json',
            base_dir / 'version_meta.json',
        ]
        for meta_path in meta_candidates:
            if meta_path.exists():
                try:
                    with open(meta_path, 'r', encoding='utf-8-sig') as f:
                        meta_data = json.load(f)
                        if meta_data.get('current_commit'):
                            info['current_commit'] = meta_data['current_commit']
                            info['latest_commit'] = meta_data['current_commit']
                        if meta_data.get('current_author'):
                            info['current_author'] = meta_data['current_author']
                        if meta_data.get('current_date'):
                            info['current_date'] = meta_data['current_date']
                            info['latest_date'] = meta_data['current_date']
                        if meta_data.get('current_message'):
                            info['current_message'] = meta_data['current_message']
                        if meta_data.get('last_updated'):
                            info['last_updated'] = meta_data['last_updated']
                    break
                except Exception as e:
                    logger.warning(f"Error reading version_meta.json: {e}")

        # Handle simulation request
        if simulate:
            sim_date = datetime.now().strftime('%b %d, %Y, %I:%M %p')
            info['latest_commit'] = '89ef12c'
            info['latest_message'] = 'Critical Security Shield & High-Concurrency Engine v2.4.2'
            info['latest_author'] = 'WhatsQ Core Team'
            info['latest_date'] = sim_date
            info['last_updated'] = info.get('current_date') or sim_date
            info['last_checked'] = sim_date
            info['update_available'] = True
            # Broadcast to event bus
            event_bus.publish('system.update_available', info)
            return info

        # 1. Get Current Local Commit from Git
        try:
            res = subprocess.run(
                ['git', '-c', 'safe.directory=*', 'rev-parse', '--short', 'HEAD'],
                cwd=base_dir,
                capture_output=True,
                text=True,
                encoding='utf-8',
                errors='replace',
                timeout=3,
                env=env
            )
            if res.returncode == 0 and res.stdout.strip():
                commit_hash = res.stdout.strip()
                info['current_commit'] = commit_hash
                info['latest_commit'] = commit_hash

                log_res = subprocess.run(
                    ['git', '-c', 'safe.directory=*', 'log', '-1', '--pretty=format:%an|%cd|%s', '--date=format:%b %d, %Y, %I:%M %p'],
                    cwd=base_dir,
                    capture_output=True,
                    text=True,
                    encoding='utf-8',
                    errors='replace',
                    timeout=3,
                    env=env
                )
                if log_res.returncode == 0 and '|' in log_res.stdout:
                    parts = log_res.stdout.split('|', 2)
                    info['current_author'] = parts[0]
                    info['current_date'] = parts[1]
                    info['current_message'] = parts[2]
                    info['latest_date'] = parts[1]
                    info['last_updated'] = parts[1]
        except Exception as e:
            logger.warning(f'Error reading local git: {e}')

        # If local commit is unknown (git failed and version_meta.json was absent),
        # skip all remote comparisons — we cannot reliably detect updates without
        # knowing what version is currently running.
        if not info.get('current_commit'):
            logger.warning('[SystemVersionView] current_commit unknown — skipping remote update check')
            info['update_available'] = False
            info['last_checked'] = datetime.now().strftime('%b %d, %Y, %I:%M %p')
            cls._cached_info = info
            cls._cache_time = now
            return info

        # 2. Check Remote Repository via git ls-remote (fast, non-rate-limited)
        remote_detected = False
        try:
            ls_res = subprocess.run(
                ['git', '-c', 'safe.directory=*', 'ls-remote', 'origin', 'refs/heads/main'],
                cwd=base_dir,
                capture_output=True,
                text=True,
                encoding='utf-8',
                errors='replace',
                timeout=6,
                env=env
            )
            if ls_res.returncode == 0 and ls_res.stdout.strip():
                parts = ls_res.stdout.strip().split()
                if parts:
                    remote_sha = parts[0]
                    remote_short = remote_sha[:7]
                    info['latest_commit'] = remote_short
                    if remote_short != info['current_commit']:
                        info['update_available'] = True
                        info['latest_message'] = 'New production build available on origin/main'
                        remote_detected = True
                    else:
                        info['update_available'] = False
                        info['latest_date'] = info['current_date']
                        remote_detected = True
        except Exception as e:
            logger.warning(f'git ls-remote failed: {e}')

        # 3. GitHub REST API — primary detection (more reliable than git ls-remote on servers)
        # Always run this; it will OVERRIDE ls-remote result if it succeeds.
        try:
            token = os.environ.get('GITHUB_TOKEN')
            headers = {'Accept': 'application/vnd.github.v3+json'}
            if token:
                headers['Authorization'] = f'Bearer {token}'

            repo_targets = ['qbscalicut/whats-q', 'vishnuwebz/whats-q']
            for target in repo_targets:
                try:
                    api_url = f'https://api.github.com/repos/{target}/commits/main'
                    resp = requests.get(api_url, headers=headers, timeout=8)
                    if resp.status_code == 200:
                        data = resp.json()
                        sha = data.get('sha', '')
                        commit_obj = data.get('commit', {})
                        short_sha = sha[:7]

                        info['latest_commit'] = short_sha
                        info['latest_message'] = commit_obj.get('message', '').split('\n')[0]
                        info['latest_author'] = commit_obj.get('author', {}).get('name', 'WhatsQ Team')

                        raw_date = commit_obj.get('author', {}).get('date', '')
                        if raw_date:
                            try:
                                dt = datetime.fromisoformat(raw_date.replace('Z', '+00:00')).astimezone()
                                info['latest_date'] = dt.strftime('%b %d, %Y, %I:%M %p')
                            except Exception:
                                info['latest_date'] = raw_date
                        else:
                            info['latest_date'] = info['current_date']

                        if short_sha and short_sha != info['current_commit']:
                            info['update_available'] = True
                            logger.info(f'Update detected via GitHub API: {info["current_commit"]} → {short_sha}')
                        else:
                            info['update_available'] = False
                            info['latest_date'] = info['current_date']
                        remote_detected = True
                        break
                except Exception as api_err:
                    logger.warning(f'GitHub API failed for {target}: {api_err}')
                    continue
        except Exception as e:
            logger.warning(f'Error querying GitHub API: {e}')

        # Normalize: only run if both methods completely failed (no remote detected)
        if not remote_detected:
            logger.warning('Could not reach remote — update detection unavailable, keeping current state')
            if not info.get('update_available'):
                info['latest_commit'] = info['current_commit']
                info['latest_author'] = info['current_author']
                info['latest_date'] = info['current_date']
                info['latest_message'] = info['current_message']

        if not info.get('last_updated'):
            info['last_updated'] = info.get('current_date')

        info['last_checked'] = datetime.now().strftime('%b %d, %Y, %I:%M %p')

        cls._cached_info = info
        cls._cache_time = now

        # If update is available, publish to SSE event bus
        if info.get('update_available'):
            event_bus.publish('system.update_available', info)

        return info

    @classmethod
    def get_update_status(cls):
        """
        Returns live progress status of the background update process.
        """
        if cls._current_update_proc is not None:
            poll = cls._current_update_proc.poll()
            if poll is None:
                elapsed = int(time.time() - getattr(cls, '_update_start_time', time.time()))
                return {
                    'in_progress': True,
                    'elapsed_seconds': elapsed,
                    'pid': cls._current_update_proc.pid,
                    'status': 'running'
                }
            else:
                proc = cls._current_update_proc
                cls._current_update_proc = None
                stdout = ''
                stderr = ''
                try:
                    out, err = proc.communicate(timeout=1)
                    stdout = out or ''
                    stderr = err or ''
                except Exception:
                    pass
                return {
                    'in_progress': False,
                    'success': (poll == 0),
                    'returncode': poll,
                    'stdout': stdout[-1500:],
                    'stderr': stderr[-1500:],
                    'status': 'completed' if poll == 0 else 'failed'
                }
        return {'in_progress': False, 'success': True, 'status': 'idle'}

    @classmethod
    def apply_update(cls):
        """
        Runs the automated backup and update script.
        Robust against missing sudo, root execution, and non-Linux environments.
        """
        cls._cached_info = None
        cls._cache_time = 0
        cls._update_start_time = time.time()
        import shutil
        from django.conf import settings

        script_candidates = [
            '/var/www/whatsq/deploy.sh',
            '/usr/local/bin/update-whatsq',
            os.path.join(settings.BASE_DIR.parent, 'deploy.sh')
        ]
        script_path = next((s for s in script_candidates if os.path.exists(s)), None)

        if script_path:
            try:
                bash_bin = shutil.which('bash') or '/bin/bash'
                cmd = [bash_bin, script_path]

                env = os.environ.copy()
                env['PATH'] = f"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{env.get('PATH', '')}"

                proc = subprocess.Popen(
                    cmd,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                    env=env
                )
                cls._current_update_proc = proc
                return {
                    'success': True,
                    'message': 'System update and PostgreSQL backup initiated successfully!',
                    'pid': proc.pid,
                    'in_progress': True
                }
            except Exception as e:
                logger.error(f"Failed to execute update script: {e}")
                return {'success': False, 'error': f"Update execution error: {str(e)}", 'in_progress': False}
        else:
            cls._current_update_proc = None
            return {
                'success': True,
                'message': 'Update simulation completed successfully on local machine.',
                'in_progress': False
            }
