# Generated by Django 5.0.14 on 2026-09-01 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=50)),
                ('avatar', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(choices=[('Lead', 'Lead'), ('Customer', 'Customer'), ('Hot Lead', 'Hot Lead'), ('Vendor', 'Vendor')], default='Lead', max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('resolved', 'Resolved'), ('ai_handled', 'AI Handled'), ('spam', 'Spam')], default='open', max_length=50)),
                ('unread_count', models.IntegerField(default=0)),
                ('lead_owner', models.CharField(default='Ramesh Kumar', max_length=100)),
                ('lead_stage', models.CharField(default='New Lead', max_length=50)),
                ('source', models.CharField(default='WhatsApp', max_length=50)),
                ('first_contact_date', models.CharField(default='May 12, 2024 10:30 AM', max_length=100)),
                ('last_contact_date', models.CharField(default='May 12, 2024 10:32 AM', max_length=100)),
                ('location', models.CharField(default='Koyilandy, Kerala', max_length=150)),
                ('language', models.CharField(default='English', max_length=50)),
                ('tags', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('service_needed', models.CharField(blank=True, default='AC Repair', max_length=150)),
                ('estimated_value', models.FloatField(default=2800.0)),
                ('active_workflow', models.CharField(default='Service Booking Flow', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(default='Welcome & Onboarding', max_length=100)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_updated', models.CharField(default='May 28, 2024', max_length=100)),
                ('author', models.CharField(default='Ayesha K.', max_length=100)),
                ('body', models.TextField()),
                ('language', models.CharField(default='English', max_length=50)),
                ('variables', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent'), ('bot', 'AI Bot'), ('system', 'System')], default='customer', max_length=20)),
                ('sender_name', models.CharField(blank=True, default='', max_length=100)),
                ('text', models.TextField()),
                ('timestamp', models.CharField(default='10:30 AM', max_length=50)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('pending', 'Pending')], default='read', max_length=20)),
                ('rich_card', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
        ),
    ]
