# Generated by Django 5.0.14 on 2026-09-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaWhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(blank=True, default='', max_length=100)),
                ('waba_id', models.CharField(blank=True, default='', max_length=100)),
                ('access_token', models.TextField(blank=True, default='')),
                ('verify_token', models.CharField(default='qiyam_whatsapp_secret_token_2026', max_length=100)),
                ('app_secret', models.CharField(blank=True, default='', max_length=100)),
                ('api_version', models.CharField(default='v21.0', max_length=20)),
                ('webhook_url', models.CharField(default='https://your-domain.com/api/conversations/webhook/', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('connection_status', models.CharField(default='disconnected', max_length=50)),
                ('business_phone_display', models.CharField(default='+91 98765 43210', max_length=50)),
                ('business_name', models.CharField(default='CoolFix Services', max_length=150)),
                ('quality_rating', models.CharField(default='GREEN', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='whatsapptemplate',
            name='variables',
        ),
        migrations.AddField(
            model_name='message',
            name='error_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='meta_message_id',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='allow_category_change',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='body_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='body_variables',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='buttons',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='footer_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='header_sample',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='header_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='header_type',
            field=models.CharField(default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='header_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='meta_category',
            field=models.CharField(choices=[('MARKETING', 'Marketing'), ('UTILITY', 'Utility'), ('AUTHENTICATION', 'Authentication')], default='UTILITY', max_length=50),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='meta_status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'In Review / Pending'), ('REJECTED', 'Rejected'), ('PAUSED', 'Paused'), ('DRAFT', 'Draft')], default='APPROVED', max_length=50),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='meta_template_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='quality_score',
            field=models.CharField(default='GREEN', max_length=50),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('pending', 'Pending'), ('failed', 'Failed')], default='read', max_length=20),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='language',
            field=models.CharField(default='en_US', max_length=50),
        ),
    ]
