# Generated by Django 5.0.14 on 2026-09-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_metawhatsappconfig_remove_whatsapptemplate_variables_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AddField(
            model_name='metawhatsappconfig',
            name='auto_reply_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='metawhatsappconfig',
            name='dual_mode_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='metawhatsappconfig',
            name='forward_webhook_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='metawhatsappconfig',
            name='staff_keywords',
            field=models.TextField(blank=True, default='staff,portal,workspace,attendance,clock,shift,leave,payroll,duty'),
        ),
        migrations.AddField(
            model_name='metawhatsappconfig',
            name='staff_numbers',
            field=models.TextField(blank=True, default=''),
        ),
    ]
