# Generated by Django 5.0.14 on 2026-09-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_seen',
            field=models.CharField(blank=True, default='Recently', max_length=100),
        ),
    ]
