# Generated by Django 5.0.14 on 2026-09-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_conversation_is_online_conversation_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='avatar',
            field=models.TextField(blank=True, default=''),
        ),
    ]
