# Generated by Django 5.0.14 on 2026-09-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_alter_conversation_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_opted_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='suppression_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
