# Generated by Django 5.0.14 on 2026-09-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_conversation_is_blocked_conversation_is_opted_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metawhatsappconfig',
            name='business_name',
            field=models.CharField(default='Qiyam Business Solutions', max_length=150),
        ),
        migrations.AlterField(
            model_name='metawhatsappconfig',
            name='business_phone_display',
            field=models.CharField(default='+91 94963 00233', max_length=50),
        ),
        migrations.AlterField(
            model_name='metawhatsappconfig',
            name='connection_status',
            field=models.CharField(default='connected', max_length=50),
        ),
        migrations.AlterField(
            model_name='metawhatsappconfig',
            name='phone_number_id',
            field=models.CharField(blank=True, default='1307178355804150', max_length=100),
        ),
        migrations.AlterField(
            model_name='metawhatsappconfig',
            name='waba_id',
            field=models.CharField(blank=True, default='4567067243541240', max_length=100),
        ),
    ]
