# Generated by Django 5.0.14 on 2026-09-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0007_alter_metawhatsappconfig_business_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedEmployeeDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_label', models.CharField(default='Surat Wholesale Line', max_length=150)),
                ('phone_number', models.CharField(blank=True, default='', max_length=50)),
                ('employee_name', models.CharField(blank=True, default='', max_length=150)),
                ('session_token', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('status', models.CharField(default='connected', max_length=50)),
                ('device_type', models.CharField(default='WhatsApp Web Multi-Device', max_length=100)),
                ('battery_level', models.IntegerField(default=95)),
                ('is_active', models.BooleanField(default=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='sender_device',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
