# Generated by Django 5.0.14 on 2026-09-21 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0008_linkedemployeedevice_message_sender_device_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_campaign_id', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('type', models.CharField(choices=[('Marketing', 'Marketing'), ('Utility', 'Utility'), ('Authentication', 'Authentication'), ('Engagement', 'Engagement')], default='Marketing', max_length=50)),
                ('category', models.CharField(default='marketing', max_length=50)),
                ('audience_list_name', models.CharField(default='', max_length=255)),
                ('total_recipients', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('read_count', models.IntegerField(default=0)),
                ('replied_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('template_name', models.CharField(blank=True, default='', max_length=255)),
                ('message_text', models.TextField(blank=True, default='')),
                ('cost', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('created_by', models.CharField(default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkCampaignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('error_reason', models.CharField(blank=True, default='', max_length=500)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='conversations.bulkcampaign')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
