# Generated by Django 5.0.14 on 2026-09-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0009_bulk_campaign_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
