# Generated by Django 5.0.14 on 2026-09-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0010_conversation_deleted_at_conversation_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('pending', 'Pending'), ('failed', 'Failed')], default='sent', max_length=20),
        ),
    ]
