# Generated by Django 5.0.14 on 2026-09-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0011_alter_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='header_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
