# Generated by Django 5.0.14 on 2026-09-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0012_alter_whatsapptemplate_header_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='active_employee_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='conversation',
            name='active_line_device',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='conversation',
            name='active_line_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='conversation',
            name='active_line_type',
            field=models.CharField(blank=True, default='meta_cloud', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
