# Generated by Django 5.0.14 on 2026-09-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0013_conversation_active_employee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='whatsapp_lid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
