# Generated by Django 5.0.14 on 2026-09-26 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0014_conversation_whatsapp_lid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppressionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(default='Customer', max_length=150)),
                ('suppression_type', models.CharField(choices=[('opt_out_stop', 'Opt-out (STOP Keyword)'), ('opt_out_button', 'Opt-out (Template Button)'), ('blocked', 'Blocked (Meta 131051)'), ('manual', 'Manual Compliance Entry')], default='opt_out_stop', max_length=50)),
                ('reason', models.CharField(default='Customer opted out of WhatsApp messages', max_length=255)),
                ('meta_error_code', models.CharField(blank=True, default='', max_length=50)),
                ('campaign_name', models.CharField(blank=True, default='', max_length=150)),
                ('source', models.CharField(default='Inbound WhatsApp Keyword (STOP)', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='Suppressed', max_length=50)),
                ('can_resubscribe', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppression_records', to='conversations.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
