# Generated by Django 5.0.14 on 2026-09-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0016_fix_rejected_template_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCSBusinessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('qiyam_cloud', 'Built-in Qiyam RCS Gateway'), ('google_rbm', 'Google RCS Business Messaging (RBM)'), ('twilio', 'Twilio RCS Messaging'), ('sinch', 'Sinch Enterprise RCS'), ('infobip', 'Infobip RCS')], default='qiyam_cloud', max_length=50)),
                ('agent_name', models.CharField(default='Qiyam Business Solutions', max_length=150)),
                ('agent_id', models.CharField(default='qiyam-rbm-prod-agent-778', max_length=150)),
                ('brand_display_name', models.CharField(default='Qiyam Ventures (Verified)', max_length=150)),
                ('brand_logo_url', models.TextField(blank=True, default='https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80')),
                ('brand_hero_color', models.CharField(default='#059669', max_length=20)),
                ('api_key', models.TextField(blank=True, default='rcs_live_key_qiyam_2026_active')),
                ('api_secret', models.TextField(blank=True, default='sk_rcs_sec_99482716301_rbm')),
                ('webhook_url', models.CharField(default='https://your-domain.com/api/conversations/rcs/webhook/', max_length=255)),
                ('webhook_verify_token', models.CharField(default='qiyam_rcs_secret_webhook_verify_2026', max_length=100)),
                ('sms_fallback_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('connection_status', models.CharField(default='connected', max_length=50)),
                ('verified_sender', models.BooleanField(default=True)),
                ('carrier_support_jio', models.BooleanField(default=True)),
                ('carrier_support_airtel', models.BooleanField(default=True)),
                ('carrier_support_vi', models.BooleanField(default=True)),
                ('carrier_support_international', models.BooleanField(default=True)),
                ('auto_reply_enabled', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
