# Generated by Django 5.0.14 on 2026-10-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0017_rcsbusinessconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedDeviceTombstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('phone_digits', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('session_token', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('device_label', models.CharField(blank=True, default='', max_length=150)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
    ]
