# Generated by Django 5.0.14 on 2026-09-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant_name', models.CharField(default='Qiyam AI Assistant', max_length=100)),
                ('default_language', models.CharField(default='English (US)', max_length=50)),
                ('time_zone', models.CharField(default='(GMT+05:30) Asia/Kolkata', max_length=100)),
                ('response_length', models.CharField(default='Balanced', max_length=50)),
                ('enable_ai_assistant', models.BooleanField(default=True)),
                ('suggest_follow_up_questions', models.BooleanField(default=True)),
                ('use_knowledge_base_first', models.BooleanField(default=True)),
                ('user_roles', models.CharField(default='All Roles (8)', max_length=100)),
                ('data_access', models.CharField(default='Organization Data', max_length=100)),
                ('conversation_visibility', models.CharField(default='Admins Only', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='Getting Started', max_length=100)),
                ('content', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('archived', 'Archived')], default='published', max_length=50)),
                ('last_updated', models.CharField(default='May 28, 2024', max_length=100)),
                ('author', models.CharField(default='Faris Usman', max_length=100)),
                ('views', models.IntegerField(default=1245)),
                ('helpful_percent', models.IntegerField(default=96)),
            ],
        ),
    ]
