# Generated by Django 5.0.14 on 2026-09-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apt_id_str', models.CharField(default='APT-1024', max_length=50)),
                ('customer_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('service', models.CharField(default='AC Installation', max_length=150)),
                ('employee', models.CharField(default='Amit Sharma', max_length=100)),
                ('date_str', models.CharField(default='May 12, 2024', max_length=50)),
                ('time_str', models.CharField(default='10:30 AM', max_length=50)),
                ('status', models.CharField(default='confirmed', max_length=50)),
                ('duration', models.CharField(default='2h 00m', max_length=50)),
                ('location', models.CharField(default='Kozhikode, Kerala', max_length=200)),
                ('amount', models.FloatField(default=1200.0)),
                ('advance', models.FloatField(default=360.0)),
                ('payment_status', models.CharField(default='advance_paid', max_length=50)),
                ('source', models.CharField(default='WhatsApp', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id_str', models.CharField(default='EMP-001', max_length=50)),
                ('employee_name', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=100)),
                ('shift', models.CharField(default='9:00 AM - 6:00 PM', max_length=100)),
                ('check_in', models.CharField(default='9:02 AM', max_length=50)),
                ('check_out', models.CharField(blank=True, max_length=50, null=True)),
                ('work_hours', models.CharField(default='8h 59m', max_length=50)),
                ('status', models.CharField(default='present', max_length=50)),
                ('location', models.CharField(default='Kozhikode, Kerala', max_length=150)),
                ('device', models.CharField(default='Mobile App (Android)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('employee_id_str', models.CharField(default='EMP-001', max_length=50)),
                ('role', models.CharField(default='Field Technician', max_length=100)),
                ('department', models.CharField(default='AC Services', max_length=100)),
                ('phone', models.CharField(default='+91 90000 11123', max_length=50)),
                ('email', models.EmailField(default='amit.sharma@qiyam.com', max_length=254)),
                ('status', models.CharField(default='on_duty', max_length=50)),
                ('location', models.CharField(default='Kozhikode, Kerala', max_length=150)),
                ('rating', models.FloatField(default=4.8)),
                ('jobs_completed_month', models.IntegerField(default=28)),
                ('on_time_percent', models.IntegerField(default=96)),
                ('today_schedule', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(default='Grocery', max_length=100)),
                ('stock_units', models.IntegerField(default=245)),
                ('stock_value', models.FloatField(default=12250.0)),
                ('status', models.CharField(default='in_stock', max_length=50)),
                ('location', models.CharField(default='Main Warehouse Aisle 01 - Rack 02', max_length=150)),
                ('reorder_level', models.IntegerField(default=50)),
                ('reorder_qty', models.IntegerField(default=100)),
                ('supplier', models.CharField(default='Fresh Supplies Pvt. Ltd.', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id_str', models.CharField(default='JOB-1024', max_length=50)),
                ('customer_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('service', models.CharField(default='AC Installation - 1.5 Ton Inverter AC', max_length=150)),
                ('date_str', models.CharField(default='May 12, 2024', max_length=50)),
                ('time_str', models.CharField(default='10:30 AM', max_length=50)),
                ('assigned_to', models.CharField(default='Amit Sharma', max_length=100)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='in_progress', max_length=50)),
                ('priority', models.CharField(default='high', max_length=20)),
                ('location', models.CharField(default='Kozhikode, Kerala', max_length=200)),
                ('amount', models.FloatField(default=1200.0)),
                ('advance_paid', models.FloatField(default=360.0)),
                ('payment_status', models.CharField(default='partially_paid', max_length=50)),
                ('timeline', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id_str', models.CharField(default='RTE-001', max_length=50)),
                ('driver_name', models.CharField(default='Rahul Mehta', max_length=150)),
                ('phone', models.CharField(default='+91 98765 43210', max_length=50)),
                ('vehicle', models.CharField(default='KL 11 AB 1234', max_length=100)),
                ('status', models.CharField(default='in_progress', max_length=50)),
                ('stops_count', models.IntegerField(default=12)),
                ('distance_km', models.FloatField(default=65.4)),
                ('duration', models.CharField(default='3h 15m', max_length=50)),
                ('estimated_end', models.CharField(default='12:15 PM', max_length=50)),
                ('fuel_cost', models.FloatField(default=1120.0)),
                ('completed_stops', models.IntegerField(default=9)),
                ('stops', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('shifts', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('related_to', models.CharField(default='JOB-1024', max_length=100)),
                ('assignee', models.CharField(default='Amit Sharma', max_length=100)),
                ('priority', models.CharField(default='high', max_length=20)),
                ('status', models.CharField(default='in_progress', max_length=50)),
                ('due_date', models.CharField(default='May 16, 2024 10:30 AM', max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('checklist', models.JSONField(default=list)),
            ],
        ),
    ]
