# Generated by Django 5.0.14 on 2026-09-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='image_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
