# Generated by Django 5.0.14 on 2026-09-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_populate_inventory_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='avatar_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(blank=True, default='O+', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.CharField(blank=True, default='Calicut Central HQ', max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='Suresh Kumar', max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='+91 94471 10045', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, default='Family / Relative', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='joining_date',
            field=models.CharField(blank=True, default='15 March 2024', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.CharField(blank=True, default='9:00 AM – 6:00 PM', max_length=100),
        ),
    ]
