# Generated by Django 5.0.14 on 2026-09-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_employee_address_employee_avatar_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPdfTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(default='Document Template', max_length=200)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
