# Generated by Django 5.0.14 on 2026-09-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=50)),
                ('total_conversations', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('color', models.CharField(default='#3B82F6', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_str', models.CharField(max_length=50)),
                ('conversations_count', models.IntegerField(default=0)),
                ('response_time_sec', models.FloatField(default=2.6)),
                ('resolution_rate_percent', models.FloatField(default=92.6)),
            ],
        ),
        migrations.CreateModel(
            name='IntentMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_name', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
            ],
        ),
    ]
