# Generated by Django 5.0.14 on 2026-09-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(default='Koyilandy, Kerala')),
                ('total_spent', models.FloatField(default=0.0)),
                ('jobs_count', models.IntegerField(default=0)),
                ('tags', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('first_seen', models.CharField(default='May 1, 2024', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_name', models.CharField(max_length=200)),
                ('customer_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount', models.FloatField(default=12000.0)),
                ('stage', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=50)),
                ('probability', models.IntegerField(default=60)),
                ('deal_owner', models.CharField(default='Ramesh Kumar', max_length=100)),
                ('source', models.CharField(default='WhatsApp', max_length=50)),
                ('expected_close_date', models.CharField(default='May 20, 2024', max_length=50)),
                ('tags', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('related_to', models.CharField(max_length=200)),
                ('customer_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('follow_up_type', models.CharField(choices=[('call', 'Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('meeting', 'Meeting')], default='whatsapp', max_length=20)),
                ('assigned_to', models.CharField(default='Priya Sharma', max_length=100)),
                ('due_date', models.CharField(default='May 12, 2024', max_length=50)),
                ('due_time', models.CharField(default='12:00 PM', max_length=50)),
                ('status', models.CharField(choices=[('due_today', 'Due Today'), ('scheduled', 'Scheduled'), ('overdue', 'Overdue'), ('completed', 'Completed')], default='scheduled', max_length=50)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='high', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('service', models.CharField(default='AC Repair', max_length=150)),
                ('location', models.CharField(default='Koyilandy, Kerala', max_length=150)),
                ('value', models.FloatField(default=2800.0)),
                ('stage', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=50)),
                ('owner', models.CharField(default='Ramesh Kumar', max_length=100)),
                ('source', models.CharField(default='WhatsApp', max_length=50)),
                ('created_at_str', models.CharField(default='May 12, 2024 10:30 AM', max_length=100)),
                ('last_contact_str', models.CharField(default='May 12, 2024 10:30 AM', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(default=list)),
                ('next_follow_up_date', models.CharField(blank=True, max_length=50, null=True)),
                ('next_follow_up_time', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
