# Generated by Django 5.0.14 on 2026-09-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id_str', models.CharField(default='APR-1024', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('approval_type', models.CharField(default='Purchase', max_length=50)),
                ('department', models.CharField(default='Operations', max_length=100)),
                ('requested_by', models.CharField(default='Aneesh K', max_length=100)),
                ('submitted_on', models.CharField(default='May 31, 2024 10:24 AM', max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_str', models.CharField(default='May 31, 2024 10:30:45 AM', max_length=100)),
                ('workflow_action', models.CharField(default='Invoice Generation', max_length=150)),
                ('branch', models.CharField(default='Kochi Branch', max_length=100)),
                ('status', models.CharField(default='success', max_length=50)),
                ('log_level', models.CharField(default='Info', max_length=50)),
                ('message', models.TextField(default='Invoice INV-2024-1056 generated successfully.')),
                ('triggered_by', models.CharField(default='System', max_length=50)),
                ('duration', models.CharField(default='1.23s', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(default='CRM', max_length=100)),
                ('business_function', models.CharField(default='Sales', max_length=100)),
                ('trigger_type', models.CharField(default='New WhatsApp Message', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('runs_this_month', models.IntegerField(default=156)),
                ('success_rate', models.FloatField(default=98.7)),
                ('last_modified', models.CharField(default='May 31, 2024 10:30 AM', max_length=100)),
                ('nodes', models.JSONField(default=list)),
                ('edges', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(default='CRM', max_length=100)),
                ('business_function', models.CharField(default='Sales', max_length=100)),
                ('description', models.TextField()),
                ('template_type', models.CharField(default='Official', max_length=50)),
                ('used_count', models.IntegerField(default=24)),
            ],
        ),
    ]
