# Generated by Django 5.0.14 on 2026-09-24 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHoursConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.JSONField(default=list)),
                ('away_message', models.TextField(default='Hi there! Thanks for reaching out to WhatsQ. Our team is currently away from the desk. We will get back to you promptly when we open tomorrow morning!')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordTriggerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('triggered_count', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('keywords', models.JSONField(default=list)),
                ('action_type', models.CharField(choices=[('reply', 'Reply with Message'), ('workflow', 'Trigger Workflow'), ('both', 'Reply and Trigger Workflow')], default='workflow', max_length=50)),
                ('workflow_name', models.CharField(blank=True, default='', max_length=200)),
                ('reply', models.TextField(blank=True, default='')),
                ('attachment', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keyword_rules', to='automation.workflow')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
