import {
  BulkCampaign,
  BulkContact,
  BulkRecipientList,
  BulkScheduledMessage,
  BulkTemplateItem,
  MetaWalletInfo,
  MetaWalletTransaction,
} from '../types';

export const initialMetaWallet: MetaWalletInfo = {
  balance: 2450.00,
  currency: 'INR',
  autoDeduct: true,
  lowBalanceThreshold: 500.00,
  autoRecharge: true,
  autoRechargeAmount: 1000.00,
  conversationPricing: {
    marketing: 0.78,
    utility: 0.30,
    authentication: 0.12,
    service: 0.00,
  },
  lastUpdated: 'May 12, 2024',
  wabaId: 'WABA-109283746501',
  paymentMethod: 'Credit Card (ending in 4242) via Meta Payments',
  officialBillingUrl: 'https://business.facebook.com/billing_hub/',
};

export const initialWalletTransactions: MetaWalletTransaction[] = [
  {
    id: 'tx-101',
    type: 'debit',
    category: 'Campaign Messages',
    amount: 967.20,
    currency: '₹',
    description: '1,240 Marketing messages for campaign "May Offers"',
    timestamp: 'May 12, 2024, 10:15 AM',
    balanceAfter: 2450.00,
    campaignId: 'cmp-1',
    campaignName: 'May Offers',
  },
  {
    id: 'tx-102',
    type: 'debit',
    category: 'Utility Messages',
    amount: 128.40,
    currency: '₹',
    description: '856 Utility reminder messages for "Appointment Reminder"',
    timestamp: 'May 10, 2024, 09:20 AM',
    balanceAfter: 3417.20,
    campaignId: 'cmp-2',
    campaignName: 'Appointment Reminder',
  },
  {
    id: 'tx-103',
    type: 'credit',
    category: 'Wallet Top-up',
    amount: 3000.00,
    currency: '₹',
    description: 'Meta Business Manager Automatic Prepaid Line Reload (HDFC Corp Credit Card ••4242)',
    timestamp: 'May 8, 2024, 02:00 PM',
    balanceAfter: 3545.60,
  },
  {
    id: 'tx-104',
    type: 'debit',
    category: 'Campaign Messages',
    amount: 1829.88,
    currency: '₹',
    description: '2,346 Marketing messages for "New Service Launch"',
    timestamp: 'May 5, 2024, 11:45 AM',
    balanceAfter: 545.60,
    campaignId: 'cmp-3',
    campaignName: 'New Service Launch',
  },
  {
    id: 'tx-105',
    type: 'credit',
    category: 'Wallet Top-up',
    amount: 290.00,
    currency: '₹',
    description: 'Meta Monthly Tier Credit (First 1,000 Free Service Conversations)',
    timestamp: 'May 1, 2024, 12:00 AM',
    balanceAfter: 2375.48,
  },
];

const rawBulkCampaigns = [
  {
    id: 'cmp-1',
    name: 'May Offers',
    description: 'Promotional campaign for May offers',
    type: 'Marketing',
    recipients: 1240,
    delivered: 1198,
    deliveredPercent: 96.6,
    failed: 42,
    failedPercent: 3.4,
    pending: 0,
    createdOn: 'May 12, 2024',
    createdBy: 'Rahul Mehta',
    scheduledOn: 'May 12, 2024, 10:30 AM',
    completedOn: 'May 12, 2024, 11:05 AM',
    status: 'Completed',
    templateName: 'Offer Announcement',
    messageText: '🎉 Special May Offers!\nGet up to 50% off on all AC repair and diagnostic services.\n\nBook now and make the most of this limited time offer!\n\nFor more details, visit our website.',
  },
  {
    id: 'cmp-2',
    name: 'Appointment Reminder',
    description: 'Appointment notifications',
    type: 'Utility',
    recipients: 856,
    delivered: 820,
    deliveredPercent: 95.8,
    failed: 36,
    failedPercent: 4.2,
    pending: 0,
    createdOn: 'May 10, 2024',
    createdBy: 'Amit Verma',
    scheduledOn: 'May 10, 2024, 09:00 AM',
    completedOn: 'May 10, 2024, 09:40 AM',
    status: 'Completed',
    templateName: 'Appointment Reminder',
    messageText: 'Hi {{1}},\nThis is a reminder for your upcoming appointment on {{2}} at {{3}}.\n\nLooking forward to seeing you!',
  },
  {
    id: 'cmp-3',
    name: 'New Service Launch',
    description: 'Service announcement',
    type: 'Marketing',
    recipients: 2346,
    delivered: 2220,
    deliveredPercent: 94.7,
    failed: 126,
    failedPercent: 5.3,
    pending: 0,
    createdOn: 'May 5, 2024',
    createdBy: 'Priya Sharma',
    scheduledOn: 'May 5, 2024, 09:00 AM',
    completedOn: 'May 5, 2024, 10:15 AM',
    status: 'Completed',
    templateName: 'Welcome Message',
    messageText: 'Hello {{1}}, we are excited to launch our 24/7 emergency repair services in your area. Call or reply now!',
  },
  {
    id: 'cmp-4',
    name: 'Payment Reminder',
    description: 'Payment follow-up',
    type: 'Utility',
    recipients: 412,
    delivered: 395,
    deliveredPercent: 95.9,
    failed: 17,
    failedPercent: 4.1,
    pending: 0,
    createdOn: 'Apr 28, 2024',
    createdBy: 'Suresh Yadav',
    status: 'Completed',
    templateName: 'Payment Reminder',
    messageText: 'Dear {{1}}, your invoice {{2}} is due. Please pay to keep your AMC service active.',
  },
  {
    id: 'cmp-5',
    name: 'Festival Greetings',
    description: 'Seasonal message',
    type: 'Marketing',
    recipients: 1890,
    delivered: 1812,
    deliveredPercent: 95.9,
    failed: 78,
    failedPercent: 4.1,
    pending: 0,
    createdOn: 'Apr 20, 2024',
    createdBy: 'Neha Patel',
    status: 'Completed',
    templateName: 'Offer Announcement',
    messageText: 'Warm festival greetings from CoolFix! Enjoy 20% off all bookings using code FEST20.',
  },
  {
    id: 'cmp-6',
    name: 'Feedback Request',
    description: 'Customer feedback',
    type: 'Engagement',
    recipients: 980,
    delivered: 912,
    deliveredPercent: 93.1,
    failed: 68,
    failedPercent: 6.9,
    pending: 0,
    createdOn: 'Apr 15, 2024',
    createdBy: 'Arjun Nair',
    status: 'Completed',
    templateName: 'Feedback Request',
    messageText: 'Hi {{1}}, how was your service experience? Rate us from 1 to 5 to help us serve you better.',
  },
  {
    id: 'cmp-7',
    name: 'Account Verification',
    description: 'Security alert',
    type: 'Security',
    recipients: 640,
    delivered: 589,
    deliveredPercent: 92.0,
    failed: 51,
    failedPercent: 8.0,
    pending: 0,
    createdOn: 'Apr 10, 2024',
    createdBy: 'Rahul Mehta',
    status: 'Failed',
    templateName: 'Account Verification',
    messageText: 'Your account verification OTP is {{1}}. Valid for 10 minutes.',
  },
  {
    id: 'cmp-8',
    name: 'Welcome Series',
    description: 'Onboarding message',
    type: 'Utility',
    recipients: 520,
    delivered: 510,
    deliveredPercent: 98.1,
    failed: 10,
    failedPercent: 1.9,
    pending: 0,
    createdOn: 'Apr 2, 2024',
    createdBy: 'Priya Sharma',
    status: 'Completed',
    templateName: 'Welcome Message',
    messageText: 'Welcome to the CoolFix family, {{1}}! Save this number for instant priority bookings.',
  },
  {
    id: 'cmp-9',
    name: 'Service Update',
    description: 'System notification',
    type: 'Utility',
    recipients: 1120,
    delivered: 1068,
    deliveredPercent: 95.4,
    failed: 52,
    failedPercent: 4.6,
    pending: 0,
    createdOn: 'Mar 28, 2024',
    createdBy: 'Amit Verma',
    status: 'Completed',
    templateName: 'Service Update',
    messageText: 'Notice: Our helpline hours are now extended to 10:00 PM every day.',
  },
  {
    id: 'cmp-10',
    name: 'Year End Offer',
    description: 'Promotional campaign',
    type: 'Marketing',
    recipients: 3450,
    delivered: 3201,
    deliveredPercent: 92.8,
    failed: 249,
    failedPercent: 7.2,
    pending: 0,
    createdOn: 'Mar 20, 2024',
    createdBy: 'Suresh Yadav',
    status: 'Completed',
    templateName: 'Offer Announcement',
    messageText: 'Year end clearance discount on all AC maintenance packages!',
  },
];

export const initialBulkCampaigns: BulkCampaign[] = rawBulkCampaigns.map((c) => ({
  ...c,
  totalRecipients: c.recipients,
  deliveredCount: c.delivered,
  readCount: Math.round(c.delivered * 0.74),
  repliedCount: Math.round(c.delivered * 0.12),
  failedCount: c.failed,
  cost: Number((c.recipients * 0.78).toFixed(2)),
  audienceListName: 'All Active Customers',
  createdAt: c.createdOn,
  status: c.status.toUpperCase(),
}));

const rawBulkTemplates = [
  {
    id: 'tpl-1',
    name: 'Appointment Reminder',
    templateId: 'appointment_reminder_01',
    category: 'Appointments',
    language: 'English',
    status: 'Approved',
    lastUpdated: 'May 10, 2024',
    updatedBy: 'Rahul Mehta',
    approvedOn: 'Apr 10, 2024, 02:30 PM',
    header: 'None',
    body: 'Hi {{1}},\nThis is a reminder for your appointment with {{2}} on {{3}} at {{4}}.\n\nLooking forward to seeing you!\n\nThank you,\n{{5}}',
    footer: 'None',
    variables: ['Customer Name', 'Technician Name', 'Date', 'Time', 'Company Name'],
  },
  {
    id: 'tpl-2',
    name: 'Booking Confirmation',
    templateId: 'booking_confirmation',
    category: 'Appointments',
    language: 'English',
    status: 'Approved',
    lastUpdated: 'May 8, 2024',
    updatedBy: 'Priya Sharma',
    approvedOn: 'Apr 5, 2024, 11:15 AM',
    body: 'Hello {{1}}, your booking for {{2}} has been confirmed for {{3}} at {{4}}.\n\nBooking ID: {{5}}.\nOur certified technician will arrive on schedule.',
    footer: 'CoolFix Services',
    variables: ['Customer Name', 'Service Name', 'Date', 'Time', 'Booking ID'],
  },
  {
    id: 'tpl-3',
    name: 'Payment Reminder',
    templateId: 'payment_reminder',
    category: 'Payments',
    language: 'English',
    status: 'Approved',
    lastUpdated: 'May 5, 2024',
    updatedBy: 'Amit Verma',
    approvedOn: 'Mar 25, 2024, 04:00 PM',
    body: 'Dear {{1}},\nThis is a friendly reminder that invoice #{{2}} for ₹{{3}} is pending. Due date: {{4}}.\n\nTap below to pay securely.',
    footer: 'Accounts Dept • CoolFix',
    variables: ['Customer Name', 'Invoice #', 'Amount', 'Due Date'],
  },
  {
    id: 'tpl-4',
    name: 'Offer Announcement',
    templateId: 'offer_announcement',
    category: 'Marketing',
    language: 'English',
    status: 'Approved',
    lastUpdated: 'Apr 28, 2024',
    updatedBy: 'Sneha Joshi',
    approvedOn: 'Apr 15, 2024, 01:20 PM',
    body: 'Special offer for you, {{1}}!\nGet up to 50% off on all AC repair and comprehensive maintenance bookings this week.\n\nUse code {{2}} on booking.',
    footer: 'Limited Time Offer',
    variables: ['Customer Name', 'Coupon Code'],
  },
  {
    id: 'tpl-5',
    name: 'Welcome Message',
    templateId: 'welcome_message',
    category: 'General',
    language: 'English',
    status: 'Approved',
    lastUpdated: 'Apr 20, 2024',
    updatedBy: 'Rahul Mehta',
    approvedOn: 'Mar 10, 2024, 10:00 AM',
    body: 'Welcome to CoolFix Services, {{1}}!\nWe provide top-rated HVAC, plumbing, electrical, and facility solutions.\nSave this contact to book services anytime on WhatsApp.',
    footer: 'CoolFix Business Solutions',
    variables: ['Customer Name'],
  },
  {
    id: 'tpl-6',
    name: 'Service Update',
    templateId: 'service_update',
    category: 'Operations',
    language: 'English',
    status: 'Pending',
    lastUpdated: 'Apr 18, 2024',
    updatedBy: 'Neha Patel',
    body: 'Hi {{1}},\nSpecialist {{2}} is en route for your service booking {{3}}. Estimated arrival: {{4}}.',
    footer: 'CoolFix Operations',
    variables: ['Customer Name', 'Technician Name', 'Booking ID', 'ETA'],
  },
  {
    id: 'tpl-7',
    name: 'Feedback Request',
    templateId: 'feedback_request',
    category: 'Customer Support',
    language: 'English',
    status: 'Approved',
    lastUpdated: 'Apr 12, 2024',
    updatedBy: 'Arjun Nair',
    approvedOn: 'Mar 20, 2024, 05:40 PM',
    body: 'Hi {{1}},\nThank you for choosing CoolFix. How satisfied were you with technician {{2}}? Please reply with a rating from 1 (Poor) to 5 (Excellent).',
    footer: 'Your feedback matters to us',
    variables: ['Customer Name', 'Technician Name'],
  },
  {
    id: 'tpl-8',
    name: 'Account Verification',
    templateId: 'account_verification',
    category: 'Security',
    language: 'English',
    status: 'Rejected',
    lastUpdated: 'Apr 10, 2024',
    updatedBy: 'Amit Sharma',
    body: 'Your verification passcode is {{1}}. Valid for 10 minutes. For security, never share this code with anyone.',
    footer: 'CoolFix Security',
    variables: ['OTP Code'],
  },
  {
    id: 'tpl-9',
    name: 'Subscription Expiry',
    templateId: 'subscription_expiry',
    category: 'Billing',
    language: 'English',
    status: 'Approved',
    lastUpdated: 'Apr 5, 2024',
    updatedBy: 'Priya Sharma',
    approvedOn: 'Mar 15, 2024, 03:10 PM',
    body: 'Hello {{1}},\nYour annual maintenance plan for {{2}} expires on {{3}}. Renew before expiry to retain free emergency service callouts.',
    footer: 'CoolFix Membership',
    variables: ['Customer Name', 'Plan Name', 'Expiry Date'],
  },
  {
    id: 'tpl-10',
    name: 'Custom Notification',
    templateId: 'custom_notification',
    category: 'Other',
    language: 'English',
    status: 'Pending',
    lastUpdated: 'Apr 2, 2024',
    updatedBy: 'Rahul Mehta',
    body: 'Dear {{1}},\nPlease note our service branches will operate on revised timings on {{2}} due to {{3}}.',
    footer: 'Notice',
    variables: ['Customer Name', 'Date', 'Occasion'],
  },
];

export const initialBulkTemplates: BulkTemplateItem[] = rawBulkTemplates.map((t) => {
  let headerType = 'NONE';
  let headerContent: string | undefined = undefined;
  let headerFileName: string | undefined = undefined;
  let headerFileSize: string | undefined = undefined;

  if (t.id === 'tpl-1' || t.id === 'tpl-4') {
    headerType = 'IMAGE';
    headerContent = 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600&q=80';
    headerFileName = 'diwali_mega_sale_flyer.jpg';
    headerFileSize = '420 KB';
  } else if (t.id === 'tpl-2' || t.id === 'tpl-5') {
    headerType = 'DOCUMENT';
    headerContent = 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf';
    headerFileName = 'CoolFix_Comprehensive_Service_Catalog.pdf';
    headerFileSize = '2.4 MB';
  } else if (t.id === 'tpl-3') {
    headerType = 'DOCUMENT';
    headerContent = 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf';
    headerFileName = 'Official_Invoice_Summary_Guide.pdf';
    headerFileSize = '1.1 MB';
  }

  const rawStatus = (t.status || 'Approved').toUpperCase();

  return {
    ...t,
    bodyText: t.body,
    qualityRating: 'High',
    headerType,
    headerContent,
    headerFileName,
    headerFileSize,
    footerText: t.footer && t.footer !== 'None' ? t.footer : 'Reply STOP to unsubscribe',
    buttons: [{ type: 'URL', text: 'View Details' }],
    status: rawStatus,
    meta_status: rawStatus,
  };
});

const rawBulkRecipientLists = [
  {
    id: 'lst-1',
    name: 'Active Customers',
    description: 'Regular customers who made at least one purchase in last 6 months',
    type: 'Customers',
    contacts: 1245,
    createdOn: 'May 10, 2024, 10:15 AM',
    createdBy: 'Rahul Mehta',
    lastUpdated: 'May 12, 2024, 11:30 AM',
    status: 'Active',
    sources: { manual: 45, website: 30, csv: 20, other: 5 },
  },
  {
    id: 'lst-2',
    name: 'New Leads - May',
    description: 'Inbound leads from website contact forms and WhatsApp ad campaigns',
    type: 'Leads',
    contacts: 856,
    createdOn: 'May 8, 2024',
    createdBy: 'Priya Sharma',
    status: 'Active',
    sources: { manual: 20, website: 60, csv: 15, other: 5 },
  },
  {
    id: 'lst-3',
    name: 'Salon Clients',
    description: 'Beauty & wellness commercial maintenance accounts',
    type: 'Customers',
    contacts: 2340,
    createdOn: 'May 5, 2024',
    createdBy: 'Amit Verma',
    status: 'Active',
    sources: { manual: 50, website: 20, csv: 25, other: 5 },
  },
  {
    id: 'lst-4',
    name: 'Festival Offer 2024',
    description: 'Special festive campaign segment for seasonal discounts',
    type: 'Campaign',
    contacts: 1890,
    createdOn: 'Apr 20, 2024',
    createdBy: 'Neha Patel',
    status: 'Active',
    sources: { manual: 30, website: 40, csv: 20, other: 10 },
  },
  {
    id: 'lst-5',
    name: 'Inactive Customers',
    description: 'No bookings or inquiries in the last 6 months',
    type: 'Customers',
    contacts: 980,
    createdOn: 'Apr 18, 2024',
    createdBy: 'Suresh Yadav',
    status: 'Inactive',
    sources: { manual: 60, website: 10, csv: 25, other: 5 },
  },
  {
    id: 'lst-6',
    name: 'High Value Customers',
    description: 'Commercial & luxury residence clients with orders above ₹10,000',
    type: 'VIP',
    contacts: 520,
    createdOn: 'Apr 12, 2024',
    createdBy: 'Rahul Mehta',
    status: 'Active',
    sources: { manual: 70, website: 15, csv: 10, other: 5 },
  },
  {
    id: 'lst-7',
    name: 'Newsletter Subscribers',
    description: 'Opted-in marketing and tips email/WhatsApp subscribers',
    type: 'General',
    contacts: 3450,
    createdOn: 'Apr 5, 2024',
    createdBy: 'Priya Sharma',
    status: 'Active',
    sources: { manual: 10, website: 75, csv: 10, other: 5 },
  },
  {
    id: 'lst-8',
    name: 'Appointment Leads',
    description: 'Customers with open appointment inquiries',
    type: 'Leads',
    contacts: 1120,
    createdOn: 'Mar 28, 2024',
    createdBy: 'Amit Verma',
    status: 'Active',
    sources: { manual: 35, website: 45, csv: 15, other: 5 },
  },
  {
    id: 'lst-9',
    name: 'Payment Pending',
    description: 'Customers with unpaid invoices or pending quotation approvals',
    type: 'Follow-up',
    contacts: 640,
    createdOn: 'Mar 15, 2024',
    createdBy: 'Neha Patel',
    status: 'Active',
    sources: { manual: 80, website: 5, csv: 10, other: 5 },
  },
  {
    id: 'lst-10',
    name: 'Test List',
    description: 'Internal QA & test phone numbers for previewing campaigns',
    type: 'General',
    contacts: 100,
    createdOn: 'Mar 1, 2024',
    createdBy: 'Rahul Mehta',
    status: 'Active',
    sources: { manual: 100, website: 0, csv: 0, other: 0 },
  },
];

export const SAMPLE_CONTACTS_POOL: Omit<BulkContact, 'id'>[] = [
  { name: 'Dr. Tariq Al-Mansoor', phone: '+966 50 123 4567', email: 'tariq.mansoor@almansoor.med', tag: 'VIP', validWhatsApp: true, optedOut: false, lastActive: '2 hours ago', source: 'Website' },
  { name: 'Rahul Sharma', phone: '+91 98765 43210', email: 'rahul.sharma@techcorp.in', tag: 'VIP', validWhatsApp: true, optedOut: false, lastActive: 'Yesterday', source: 'CRM' },
  { name: 'Amina Al-Balushi', phone: '+968 9123 4567', email: 'amina.b@muscatlogistics.om', tag: 'Loyal', validWhatsApp: true, optedOut: false, lastActive: '3 days ago', source: 'WhatsApp' },
  { name: 'Vikram Menon', phone: '+91 94470 12345', email: 'vikram.menon@koyilandy.com', tag: 'Corporate', validWhatsApp: true, optedOut: false, lastActive: 'Today', source: 'Referral' },
  { name: 'Zainab Qasim', phone: '+971 52 345 6789', email: 'zainab.q@dubaifacilities.ae', tag: 'Loyal', validWhatsApp: true, optedOut: false, lastActive: '5 hours ago', source: 'Website' },
  { name: 'Sneha Joshi', phone: '+91 98234 56789', email: 'sneha.j@punehomes.com', tag: 'Retail', validWhatsApp: true, optedOut: false, lastActive: '1 day ago', source: 'Campaign' },
  { name: 'Mohammed Al-Fayed', phone: '+966 55 987 6543', email: 'alfayed@jeddahproperties.sa', tag: 'VIP', validWhatsApp: true, optedOut: false, lastActive: 'Today', source: 'CRM' },
  { name: 'Arjun Nair', phone: '+91 97456 12389', email: 'arjun.nair@kochicooling.in', tag: 'Corporate', validWhatsApp: true, optedOut: false, lastActive: '2 days ago', source: 'Website' },
  { name: 'Fatima Zahra', phone: '+971 50 789 0123', email: 'fatima.z@alzahra.ae', tag: 'VIP', validWhatsApp: true, optedOut: false, lastActive: '4 hours ago', source: 'WhatsApp' },
  { name: 'Rajesh Pillai', phone: '+91 98471 99887', email: 'rajesh.p@calicutmarine.com', tag: 'Retail', validWhatsApp: true, optedOut: false, lastActive: 'Just now', source: 'Direct' },
  { name: 'Nasser Al-Harthy', phone: '+968 9234 5678', email: 'nasser@omanindustrial.com', tag: 'Corporate', validWhatsApp: true, optedOut: false, lastActive: 'Yesterday', source: 'Manual' },
  { name: 'Pooja Hegde', phone: '+91 91234 88776', email: 'pooja.h@bangalorelifestyle.com', tag: 'Loyal', validWhatsApp: true, optedOut: false, lastActive: '3 days ago', source: 'Website' },
  { name: 'Abdulrahman Al-Nuaimi', phone: '+971 56 443 2211', email: 'nuaimi@sharjahholdings.ae', tag: 'VIP', validWhatsApp: true, optedOut: false, lastActive: 'Today', source: 'CRM' },
  { name: 'Kavita Sundaram', phone: '+91 94462 33445', email: 'kavita.s@chennaibuilders.in', tag: 'Retail', validWhatsApp: true, optedOut: false, lastActive: '4 days ago', source: 'WhatsApp' },
  { name: 'Omar Bin Rashid', phone: '+966 54 332 1100', email: 'omar.rashid@riyadhtrading.com', tag: 'VIP', validWhatsApp: true, optedOut: false, lastActive: 'Yesterday', source: 'Referral' },
  { name: 'Siddharth Rao', phone: '+91 99887 76655', email: 'siddharth@hyderabadrealtors.com', tag: 'Corporate', validWhatsApp: true, optedOut: false, lastActive: '2 days ago', source: 'Website' },
  { name: 'Laila Al-Kuwari', phone: '+974 5512 3456', email: 'laila@dohaservices.qa', tag: 'Loyal', validWhatsApp: true, optedOut: false, lastActive: '5 days ago', source: 'Campaign' },
  { name: 'Ananya Deshmukh', phone: '+91 98200 11223', email: 'ananya@mumbaidesign.in', tag: 'Retail', validWhatsApp: true, optedOut: false, lastActive: 'Today', source: 'Website' },
  { name: 'Inactive Contact (Opted Out)', phone: '+91 80000 00000', email: 'optout@sample.com', tag: 'Opt-Out', validWhatsApp: false, optedOut: true, lastActive: '6 months ago', source: 'Unsubscribe' },
  { name: 'Unverified Lead', phone: '+91 70000 11111', email: 'unverified@test.com', tag: 'Unverified', validWhatsApp: false, optedOut: false, lastActive: '1 month ago', source: 'CSV' },
];

export const getSampleContactsForList = (listId: string, listName: string): BulkContact[] => {
  return SAMPLE_CONTACTS_POOL.map((c, index) => ({
    ...c,
    id: `cnt-${listId}-${index + 1}`,
  }));
};

export const initialBulkRecipientLists: BulkRecipientList[] = rawBulkRecipientLists.map((l) => ({
  ...l,
  contactCount: l.contacts,
  validWhatsAppCount: Math.round(l.contacts * 0.98),
  tags: ['VIP', 'Active', 'Marketing'],
  createdAt: l.createdOn,
  lastUsedAt: l.lastUpdated,
  contactItems: getSampleContactsForList(l.id, l.name),
}));

const rawBulkScheduledMessages = [
  {
    id: 'sch-1',
    name: 'May Offers Campaign',
    description: 'Promotional offers for May',
    type: 'Campaign',
    scheduledDateTime: 'May 12, 2024 10:00 AM',
    scheduledDate: 'May 12, 2024',
    scheduledTime: '10:00 AM',
    recipients: 1240,
    status: 'Pending',
    createdBy: 'Rahul Mehta',
    createdOn: 'May 10, 2024, 02:15 PM',
    templateUsed: 'May Offer - Template',
    messageText: '🎉 Special May Offers!\nGet up to 50% off on our services.\n\nBook now and make the most of this limited time offer!\n\nFor more details, visit our website.',
  },
  {
    id: 'sch-2',
    name: 'Appointment Reminders',
    description: 'Salon appointments reminder blast',
    type: 'Transactional',
    scheduledDateTime: 'May 10, 2024 09:00 AM',
    scheduledDate: 'May 10, 2024',
    scheduledTime: '09:00 AM',
    recipients: 856,
    status: 'Pending',
    createdBy: 'Amit Verma',
    createdOn: 'May 8, 2024',
    templateUsed: 'Appointment Reminder',
    messageText: 'Friendly reminder about your scheduled visit tomorrow.',
  },
  {
    id: 'sch-3',
    name: 'Festival Greetings',
    description: 'Onam special wishes to all customers',
    type: 'Campaign',
    scheduledDateTime: 'May 15, 2024 08:00 AM',
    scheduledDate: 'May 15, 2024',
    scheduledTime: '08:00 AM',
    recipients: 1890,
    status: 'Pending',
    createdBy: 'Neha Patel',
    createdOn: 'May 9, 2024',
    templateUsed: 'Festival Greeting Card',
    messageText: 'Warm wishes on this festive season from CoolFix team!',
  },
  {
    id: 'sch-4',
    name: 'Payment Follow-up',
    description: 'Pending payments reminder',
    type: 'Transactional',
    scheduledDateTime: 'May 11, 2024 11:30 AM',
    scheduledDate: 'May 11, 2024',
    scheduledTime: '11:30 AM',
    recipients: 412,
    status: 'Sent',
    createdBy: 'Suresh Yadav',
    createdOn: 'May 5, 2024',
    templateUsed: 'Payment Reminder',
    messageText: 'Gentle reminder regarding pending invoice due this week.',
  },
  {
    id: 'sch-5',
    name: 'New Service Launch',
    description: 'Service announcement blast',
    type: 'Campaign',
    scheduledDateTime: 'May 5, 2024 09:00 AM',
    scheduledDate: 'May 5, 2024',
    scheduledTime: '09:00 AM',
    recipients: 2346,
    status: 'Sent',
    createdBy: 'Priya Sharma',
    createdOn: 'Apr 30, 2024',
    templateUsed: 'Offer Announcement',
    messageText: 'Introducing our brand new 24/7 HVAC care service.',
  },
  {
    id: 'sch-6',
    name: 'Feedback Request',
    description: 'Customer feedback survey',
    type: 'Transactional',
    scheduledDateTime: 'May 8, 2024 04:00 PM',
    scheduledDate: 'May 8, 2024',
    scheduledTime: '04:00 PM',
    recipients: 980,
    status: 'Pending',
    createdBy: 'Arjun Nair',
    createdOn: 'May 6, 2024',
    templateUsed: 'Feedback Request',
    messageText: 'Please share your quick feedback on our technician service.',
  },
  {
    id: 'sch-7',
    name: 'Newsletter - May',
    description: 'Monthly updates & maintenance tips',
    type: 'Campaign',
    scheduledDateTime: 'May 18, 2024 10:00 AM',
    scheduledDate: 'May 18, 2024',
    scheduledTime: '10:00 AM',
    recipients: 3450,
    status: 'Pending',
    createdBy: 'Priya Sharma',
    createdOn: 'May 11, 2024',
    templateUsed: 'Welcome Message',
    messageText: 'Your monthly guide to energy saving and AC health.',
  },
  {
    id: 'sch-8',
    name: 'Inactive Customer Re-engagement',
    description: 'Win back campaign with special 30% discount',
    type: 'Campaign',
    scheduledDateTime: 'May 20, 2024 09:30 AM',
    scheduledDate: 'May 20, 2024',
    scheduledTime: '09:30 AM',
    recipients: 640,
    status: 'Pending',
    createdBy: 'Suresh Yadav',
    createdOn: 'May 12, 2024',
    templateUsed: 'Offer Announcement',
    messageText: 'We miss you! Here is an exclusive 30% discount on your next booking.',
  },
  {
    id: 'sch-9',
    name: 'Welcome Series - Part 1',
    description: 'New user onboarding sequence',
    type: 'Transactional',
    scheduledDateTime: 'May 22, 2024 11:00 AM',
    scheduledDate: 'May 22, 2024',
    scheduledTime: '11:00 AM',
    recipients: 520,
    status: 'Pending',
    createdBy: 'Rahul Mehta',
    createdOn: 'May 14, 2024',
    templateUsed: 'Welcome Message',
    messageText: 'Getting started with CoolFix: how to request emergency visits on WhatsApp.',
  },
  {
    id: 'sch-10',
    name: 'Year End Offer Reminder',
    description: 'Last chance deals',
    type: 'Campaign',
    scheduledDateTime: 'May 28, 2024 02:00 PM',
    scheduledDate: 'May 28, 2024',
    scheduledTime: '02:00 PM',
    recipients: 1120,
    status: 'Pending',
    createdBy: 'Rahul Mehta',
    createdOn: 'May 15, 2024',
    templateUsed: 'Offer Announcement',
    messageText: 'Final reminder: Annual maintenance promo ends in 48 hours!',
  },
];

export const initialBulkScheduledMessages: BulkScheduledMessage[] = rawBulkScheduledMessages.map(
  (s) => ({
    ...s,
    campaignName: s.name,
    recipientGroupName: 'All Active Customers',
    recipientCount: s.recipients,
    scheduledFor: s.scheduledDateTime,
    templateName: s.templateUsed || 'Offer Announcement',
    category: 'marketing',
    status: s.status === 'Pending' ? 'QUEUED' : 'SENT',
    estimatedCost: Number((s.recipients * 0.78).toFixed(2)),
  })
);
