import {
  InventoryItem, Lead, Deal, FollowUp, Job, Employee,
  AttendanceRecord, Task, Route, Transaction, Invoice, Quotation, Expense, PaymentAccount
} from '../types';

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 1,
    name: 'Basmati Rice 5kg',
    sku: 'GROC-001',
    category: 'Grocery',
    stock_units: 245,
    stock_value: 12250.0,
    status: 'in_stock',
    location: 'Main Warehouse Aisle 01 - Rack 02',
    reorder_level: 50,
    reorder_qty: 100,
    supplier: 'Fresh Supplies Pvt. Ltd.',
    image_url: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 2,
    name: 'Sunflower Oil 1L',
    sku: 'GROC-002',
    category: 'Grocery',
    stock_units: 28,
    stock_value: 1960.0,
    status: 'low_stock',
    location: 'Main Warehouse Aisle 02 - Rack 01',
    reorder_level: 30,
    reorder_qty: 80,
    supplier: 'Fresh Supplies Pvt. Ltd.',
    image_url: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 3,
    name: 'Milk Powder 500g',
    sku: 'DAIRY-001',
    category: 'Dairy',
    stock_units: 0,
    stock_value: 0.0,
    status: 'out_of_stock',
    location: 'Main Warehouse Aisle 03 - Rack 01',
    reorder_level: 20,
    reorder_qty: 50,
    supplier: 'Milma Dairy',
    image_url: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 4,
    name: 'Colgate Toothpaste 100g',
    sku: 'HPC-001',
    category: 'Personal Care',
    stock_units: 156,
    stock_value: 3120.0,
    status: 'in_stock',
    location: 'Main Warehouse Aisle 04 - Rack 03',
    reorder_level: 40,
    reorder_qty: 100,
    supplier: 'Colgate Palmolive',
    image_url: 'https://images.unsplash.com/photo-1559591937-e10b14421b59?w=400&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_LEADS: Lead[] = [
  { id: 1, name: 'Amit Verma', phone: '+91 98765 43210', service: 'AC Repair', location: 'Koyilandy, Kerala', value: 2800.0, stage: 'new', owner: 'Ramesh Kumar', source: 'WhatsApp', created_at_str: 'May 12, 2024', last_contact_str: 'May 12, 2024', notes: 'Customer needs AC repair tomorrow morning. Prefers 10 AM - 12 PM slot.', tags: ['AC Service', 'Urgent'] },
  { id: 2, name: 'Priya Sharma', phone: '+91 89213 56789', service: 'Home Cleaning', location: 'Kozhikode, Kerala', value: 1200.0, stage: 'new', owner: 'Ramesh Kumar', source: 'WhatsApp', created_at_str: 'May 12, 2024', last_contact_str: 'May 12, 2024', notes: 'Requested quotation for 3 BHK flat.', tags: ['Cleaning'] },
  { id: 3, name: 'Rahul Singh', phone: '+91 98764 11122', service: 'Electrical Work', location: 'Koyilandy, Kerala', value: 3500.0, stage: 'new', owner: 'Ramesh Kumar', source: 'Website', created_at_str: 'May 11, 2024', last_contact_str: 'May 11, 2024', notes: 'Full house wiring check.', tags: ['Electrical'] },
  { id: 4, name: 'Neha Patel', phone: '+91 96789 11223', service: 'Plumbing', location: 'Kozhikode, Kerala', value: 2200.0, stage: 'new', owner: 'Ramesh Kumar', source: 'Referral', created_at_str: 'May 11, 2024', last_contact_str: 'May 11, 2024', notes: 'Bathroom pipe leakage.', tags: ['Plumbing'] },
  { id: 5, name: 'Vikram Mehta', phone: '+91 90000 11123', service: 'AC Installation', location: 'Calicut, Kerala', value: 4500.0, stage: 'contacted', owner: 'Priya Sharma', source: 'WhatsApp', created_at_str: 'May 10, 2024', last_contact_str: 'May 12, 2024', notes: 'Discussed installation quote.', tags: ['AC Service'] },
  { id: 6, name: 'Sneha Joshi', phone: '+91 96789 66771', service: 'Pest Control', location: 'Koyilandy, Kerala', value: 2000.0, stage: 'contacted', owner: 'Priya Sharma', source: 'Direct Call', created_at_str: 'May 10, 2024', last_contact_str: 'May 11, 2024', notes: 'Follow up scheduled for tomorrow.', tags: ['Pest Control'] },
  { id: 7, name: 'Anita Singh', phone: '+91 98765 11199', service: 'AC Repair (Split Unit)', location: 'Koyilandy, Kerala', value: 2800.0, stage: 'qualified', owner: 'Anita Singh', source: 'WhatsApp', created_at_str: 'May 09, 2024', last_contact_str: 'May 10, 2024', notes: 'Gas refill verified.', tags: ['AC Service'] },
  { id: 8, name: 'Deepak Patel', phone: '+91 85471 22330', service: 'AC Servicing (3 Units)', location: 'Calicut, Kerala', value: 5600.0, stage: 'proposal_sent', owner: 'Ramesh Kumar', source: 'WhatsApp', created_at_str: 'May 08, 2024', last_contact_str: 'May 10, 2024', notes: 'Proposal sent with 10% AMC discount.', tags: ['AC Service', 'AMC'] },
  { id: 9, name: 'Kiran Kumar', phone: '+91 81234 55667', service: 'AC Installation + Ducting', location: 'Kozhikode, Kerala', value: 12000.0, stage: 'negotiation', owner: 'Rahul Mehta', source: 'Walk-in', created_at_str: 'May 07, 2024', last_contact_str: 'May 09, 2024', notes: 'Commercial site quotation under review.', tags: ['Commercial', 'High Value'] },
];

export const INITIAL_DEALS: Deal[] = [
  { id: 1, deal_name: 'AC Installation - Vikram Mehta', customer_name: 'Vikram Mehta', phone: '+91 90000 11123', amount: 12000.0, stage: 'proposal_sent', probability: 60, deal_owner: 'Ramesh Kumar', source: 'WhatsApp', expected_close_date: 'Jun 15, 2024', tags: ['AC Service', 'High Value'], notes: 'Customer interested in 1.5 ton inverter AC installation. Shared quotation.' },
  { id: 2, deal_name: 'AC Repair AMC - Pooja Iyer', customer_name: 'Pooja Iyer', phone: '+91 96789 12345', amount: 18000.0, stage: 'proposal_sent', probability: 75, deal_owner: 'Priya Sharma', source: 'Direct Call', expected_close_date: 'Jun 18, 2024', tags: ['AMC', 'VIP'], notes: 'Annual maintenance contract for 5 AC units.' },
  { id: 3, deal_name: 'Full Home Cleaning - Anil Gupta', customer_name: 'Anil Gupta', phone: '+91 98765 22334', amount: 15000.0, stage: 'negotiation', probability: 85, deal_owner: 'Ramesh Kumar', source: 'WhatsApp', expected_close_date: 'Jun 20, 2024', tags: ['Cleaning'], notes: 'Deep cleaning prior to house warming.' },
  { id: 4, deal_name: 'AC Duct Cleaning - Kiran Kumar', customer_name: 'Kiran Kumar', phone: '+91 81234 55667', amount: 7200.0, stage: 'negotiation', probability: 80, deal_owner: 'Rahul Mehta', source: 'Referral', expected_close_date: 'Jun 22, 2024', tags: ['AC Service'], notes: 'Commercial office ducting.' },
  { id: 5, deal_name: 'AC Repair - Deepak Patel', customer_name: 'Deepak Patel', phone: '+91 85471 22330', amount: 2800.0, stage: 'won', probability: 100, deal_owner: 'Ramesh Kumar', source: 'WhatsApp', expected_close_date: 'May 30, 2024', tags: ['AC Service'], notes: 'Service completed and invoice paid.' },
];

export const INITIAL_JOBS: Job[] = [
  {
    id: 1,
    job_id_str: 'JOB-1024',
    customer_name: 'Vikram Mehta',
    phone: '+91 90000 11123',
    service: 'AC Installation - 1.5 Ton Inverter AC',
    date_str: 'May 12, 2024',
    time_str: '10:30 AM',
    assigned_to: 'Amit Sharma',
    status: 'in_progress',
    priority: 'high',
    location: 'Kozhikode, Kerala',
    amount: 1200.0,
    advance_paid: 360.0,
    payment_status: 'partially_paid',
    timeline: [
      { title: 'Job Created', timestamp: 'May 10, 10:15 AM', by: 'System', completed: true },
      { title: 'Assigned to Amit Sharma', timestamp: 'May 10, 10:20 AM', by: 'System', completed: true },
      { title: 'Customer Confirmed', timestamp: 'May 10, 11:05 AM', by: 'Customer', completed: true },
      { title: 'Job Started', timestamp: 'May 12, 10:35 AM', by: 'Amit Sharma', completed: true },
      { title: 'Job Completed', timestamp: 'Pending', by: 'Technician', completed: false },
    ]
  },
  {
    id: 2,
    job_id_str: 'JOB-1023',
    customer_name: 'Amit Verma',
    phone: '+91 98765 43210',
    service: 'AC Repair (Gas Leakage)',
    date_str: 'May 12, 2024',
    time_str: '12:00 PM',
    assigned_to: 'Priya Sharma',
    status: 'scheduled',
    priority: 'high',
    location: 'Kozhikode, Kerala',
    amount: 2800.0,
    advance_paid: 840.0,
    payment_status: 'advance_paid',
    timeline: [
      { title: 'Job Created', timestamp: 'May 11, 09:00 AM', by: 'System', completed: true },
      { title: 'Assigned to Priya Sharma', timestamp: 'May 11, 09:30 AM', by: 'System', completed: true },
      { title: 'Customer Confirmed', timestamp: 'May 11, 10:00 AM', by: 'Customer', completed: true }
    ]
  },
  {
    id: 3,
    job_id_str: 'JOB-1022',
    customer_name: 'Priya Sharma',
    phone: '+91 89213 56789',
    service: 'Deep Cleaning (Full Home)',
    date_str: 'May 13, 2024',
    time_str: '09:00 AM',
    assigned_to: 'Neha Patel',
    status: 'scheduled',
    priority: 'medium',
    location: 'Ramanattukara, Kerala',
    amount: 4500.0,
    advance_paid: 1350.0,
    payment_status: 'advance_paid',
    timeline: [
      { title: 'Job Created', timestamp: 'May 11, 02:00 PM', by: 'System', completed: true },
      { title: 'Assigned to Neha Patel', timestamp: 'May 11, 02:15 PM', by: 'System', completed: true }
    ]
  },
  {
    id: 4,
    job_id_str: 'JOB-1020',
    customer_name: 'Sneha Joshi',
    phone: '+91 96789 66771',
    service: 'AC Maintenance (General Service)',
    date_str: 'May 13, 2024',
    time_str: '04:00 PM',
    assigned_to: 'Arjun Nair',
    status: 'completed',
    priority: 'low',
    location: 'Vadakara, Kerala',
    amount: 1500.0,
    advance_paid: 1500.0,
    payment_status: 'paid',
    timeline: [
      { title: 'Job Created', timestamp: 'May 09, 10:00 AM', by: 'System', completed: true },
      { title: 'Service Completed', timestamp: 'May 13, 05:00 PM', by: 'Arjun Nair', completed: true }
    ]
  },
  {
    id: 5,
    job_id_str: 'JOB-1019',
    customer_name: 'Sunil Joseph',
    phone: '+91 90321 45000',
    service: 'Electrical Work (Wiring & Switches)',
    date_str: 'May 14, 2024',
    time_str: '10:00 AM',
    assigned_to: 'Amit Sharma',
    status: 'cancelled',
    priority: 'low',
    location: 'Kozhikode, Kerala',
    amount: 1800.0,
    advance_paid: 0.0,
    payment_status: 'pending',
    timeline: [
      { title: 'Job Created', timestamp: 'May 08, 11:00 AM', by: 'System', completed: true },
      { title: 'Customer Cancelled', timestamp: 'May 08, 02:00 PM', by: 'Customer', completed: true }
    ]
  },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  { id: 1, name: 'Amit Sharma', employee_id_str: 'EMP-001', role: 'Field Technician', department: 'AC Services', phone: '+91 90000 11123', email: 'amit.sharma@qiyam.com', status: 'on_duty', location: 'Kozhikode, Kerala', rating: 4.8, jobs_completed_month: 28, on_time_percent: 96 },
  { id: 2, name: 'Priya Sharma', employee_id_str: 'EMP-002', role: 'Customer Support', department: 'Support', phone: '+91 89213 56789', email: 'priya.sharma@qiyam.com', status: 'active', location: 'Kozhikode Office', rating: 4.6, jobs_completed_month: 120, on_time_percent: 98 },
  { id: 3, name: 'Rahul Singh', employee_id_str: 'EMP-003', role: 'Plumbing Technician', department: 'Plumbing', phone: '+91 98764 11122', email: 'rahul.singh@qiyam.com', status: 'on_duty', location: 'Vadakara, Kerala', rating: 4.7, jobs_completed_month: 22, on_time_percent: 94 },
  { id: 4, name: 'Neha Patel', employee_id_str: 'EMP-004', role: 'Housekeeper Lead', department: 'Cleaning', phone: '+91 96789 11223', email: 'neha.patel@qiyam.com', status: 'on_leave', location: 'Kozhikode, Kerala', rating: 4.5, jobs_completed_month: 18, on_time_percent: 90 },
  { id: 5, name: 'Arjun Nair', employee_id_str: 'EMP-005', role: 'Electrician', department: 'Electrical', phone: '+91 85471 22330', email: 'arjun.nair@qiyam.com', status: 'on_duty', location: 'Ramanattukara, Kerala', rating: 4.6, jobs_completed_month: 31, on_time_percent: 95 },
  { id: 6, name: 'Sneha Joshi', employee_id_str: 'EMP-006', role: 'Team Lead', department: 'AC Services', phone: '+91 96789 66771', email: 'sneha.joshi@qiyam.com', status: 'active', location: 'Kozhikode Office', rating: 4.9, jobs_completed_month: 56, on_time_percent: 99 },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  { id: 1, employee_id_str: 'EMP-001', employee_name: 'Amit Sharma', department: 'AC Services', shift: '9:00 AM - 6:00 PM', check_in: '8:58 AM', check_out: undefined, work_hours: '8h 58m', status: 'present', location: 'Kozhikode, Kerala', device: 'WhatsApp Geo-Punch (Android)' },
  { id: 2, employee_id_str: 'EMP-002', employee_name: 'Priya Sharma', department: 'Customer Support', shift: '9:00 AM - 6:00 PM', check_in: '9:02 AM', check_out: undefined, work_hours: '8h 54m', status: 'present', location: 'Kozhikode Office', device: 'WhatsApp Web (Chrome)' },
  { id: 3, employee_id_str: 'EMP-003', employee_name: 'Rahul Singh', department: 'Plumbing Services', shift: '9:00 AM - 6:00 PM', check_in: '8:50 AM', check_out: undefined, work_hours: '9h 05m', status: 'present', location: 'Vadakara, Kerala', device: 'WhatsApp Geo-Punch (iOS)' },
  { id: 4, employee_id_str: 'EMP-004', employee_name: 'Neha Patel', department: 'Housekeeping Lead', shift: '9:00 AM - 6:00 PM', check_in: '-', check_out: undefined, work_hours: '0h 00m', status: 'absent', location: 'Kozhikode, Kerala', device: 'Leave Portal (Approved)' },
  { id: 5, employee_id_str: 'EMP-005', employee_name: 'Arjun Nair', department: 'Electrical Services', shift: '9:00 AM - 6:00 PM', check_in: '9:00 AM', check_out: undefined, work_hours: '8h 56m', status: 'present', location: 'Ramanattukara, Kerala', device: 'WhatsApp Geo-Punch (Android)' },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  { id: 1, date_str: 'May 31, 2024', tx_type: 'income', description: 'Payment from AC Services', category: 'AC Services', party: 'Amit Sharma', account: 'HDFC Bank - 1234', amount: 12500.0, payment_mode: 'UPI', reference_id: 'INV-2024-0521', status: 'completed' },
  { id: 2, date_str: 'May 30, 2024', tx_type: 'expense', description: 'Salary - May 2024', category: 'Salaries & Wages', party: 'Payroll', account: 'ICICI Bank - 5678', amount: 265000.0, payment_mode: 'Bank Transfer', reference_id: 'EXP-2024-0311', status: 'completed' },
  { id: 3, date_str: 'May 29, 2024', tx_type: 'income', description: 'Digital Marketing Project', category: 'Marketing', party: 'Digital Ads', account: 'HDFC Bank - 1234', amount: 18750.0, payment_mode: 'UPI', reference_id: 'INV-2024-0518', status: 'completed' },
  { id: 4, date_str: 'May 28, 2024', tx_type: 'expense', description: 'Office Rent - May', category: 'Rent & Utilities', party: 'Landlord', account: 'Axis Bank - 9012', amount: 55000.0, payment_mode: 'NEFT', reference_id: 'EXP-2024-0308', status: 'completed' },
  { id: 5, date_str: 'May 27, 2024', tx_type: 'income', description: 'Website Development', category: 'Web Services', party: 'Rahul Singh', account: 'HDFC Bank - 1234', amount: 75000.0, payment_mode: 'Bank Transfer', reference_id: 'INV-2024-0512', status: 'completed' },
  { id: 6, date_str: 'May 26, 2024', tx_type: 'transfer', description: 'Branch Petty Cash Float Transfer', category: 'Account Transfer', party: 'Calicut Cyberpark Vault', account: 'HDFC Bank - 1234', amount: 15000.0, payment_mode: 'IMPS', reference_id: 'TRF-2024-0044', status: 'completed' },
  { id: 7, date_str: 'May 25, 2024', tx_type: 'refund', description: 'Customer Security Deposit Refund', category: 'Customer Refund', party: 'Priya Sharma', account: 'ICICI Bank - 5678', amount: 2500.0, payment_mode: 'UPI', reference_id: 'RFD-2024-0019', status: 'completed' },
];

export const INITIAL_INVOICES: Invoice[] = [
  { id: 1, invoice_number: 'INV-2024-0186', customer_name: 'AC Services', customer_email: 'acservices@gmail.com', customer_phone: '+91 98765 43210', invoice_date: 'May 31, 2024', due_date: 'Jun 14, 2024', amount: 12500.0, status: 'paid', paid_amount: 12500.0, payment_method: 'UPI', payment_date: 'May 31, 2024', items: [{ description: 'AC Repair & Gas Refill', qty: 2, unitPrice: 6250, amount: 12500 }] },
  { id: 2, invoice_number: 'INV-2024-0185', customer_name: 'Digital Ads Pvt. Ltd.', customer_email: 'info@digitalads.com', customer_phone: '+91 98765 11122', invoice_date: 'May 30, 2024', due_date: 'Jun 13, 2024', amount: 18750.0, status: 'paid', paid_amount: 18750.0, payment_method: 'Bank Transfer', payment_date: 'May 30, 2024' },
  { id: 3, invoice_number: 'INV-2024-0184', customer_name: 'Zoho Corp', customer_email: 'accounts@zohocorp.com', customer_phone: '+91 85471 22330', invoice_date: 'May 29, 2024', due_date: 'Jun 12, 2024', amount: 4200.0, status: 'partial_paid', paid_amount: 2100.0, payment_method: 'Card' },
  { id: 4, invoice_number: 'INV-2024-0183', customer_name: 'Priya Sharma', customer_email: 'priya.sharma@gmail.com', customer_phone: '+91 89213 56789', invoice_date: 'May 28, 2024', due_date: 'Jun 11, 2024', amount: 32000.0, status: 'overdue', paid_amount: 0.0, payment_method: 'UPI' },
  { id: 5, invoice_number: 'INV-2024-0182', customer_name: 'Rahul Singh', customer_email: 'rahulsingh@gmail.com', customer_phone: '+91 96789 11223', invoice_date: 'May 27, 2024', due_date: 'Jun 10, 2024', amount: 7600.0, status: 'sent', paid_amount: 0.0, payment_method: 'UPI' },
];

export const INITIAL_QUOTATIONS: Quotation[] = [
  {
    id: 1,
    quotation_number: 'QUO-2024-0042',
    customer_name: 'Dr. Tariq Rahman (Aster Clinic)',
    customer_email: 'dr.tariq@asterclinic.com',
    customer_phone: '+91 98470 12345',
    quotation_date: 'May 30, 2024',
    valid_until: 'Jun 15, 2024',
    amount: 28500,
    subtotal: 25000,
    tax_amount: 4500,
    discount_amount: 1000,
    status: 'accepted',
    converted_invoice_id: '',
    terms: 'Validity: 15 days. 50% advance payment required upon acceptance. 1-year on-site compressor warranty included.',
    notes: 'Quotation for Daikin Inverter Multi-Split system servicing & duct sanitization.',
    items: [
      { description: 'Daikin VRV System Multi-Split Deep Cleaning', qty: 4, unitPrice: 3500, taxRate: 18, amount: 14000 },
      { description: 'Eco-Friendly Antibacterial Duct Sanitization', qty: 2, unitPrice: 4000, taxRate: 18, amount: 8000 },
      { description: 'Comprehensive 1-Year AMC Maintenance Plan', qty: 1, unitPrice: 3000, taxRate: 18, amount: 3000 },
    ],
  },
  {
    id: 2,
    quotation_number: 'QUO-2024-0041',
    customer_name: 'Malabar Gold & Diamonds',
    customer_email: 'procurement@malabargold.com',
    customer_phone: '+91 97456 78901',
    quotation_date: 'May 28, 2024',
    valid_until: 'Jun 12, 2024',
    amount: 64000,
    subtotal: 60000,
    tax_amount: 10800,
    discount_amount: 6800,
    status: 'sent',
    converted_invoice_id: '',
    terms: 'Commercial showroom HVAC overhaul. Work to be completed during non-business hours.',
    notes: 'Presented directly to facility manager Mr. Najeeb. Awaiting final board sign-off.',
    items: [
      { description: 'Commercial Ceiling Cassette AC Overhaul (3 Ton)', qty: 6, unitPrice: 8000, taxRate: 18, amount: 48000 },
      { description: 'Refrigerant R32 Top-up & Gas Leak Hydro-Testing', qty: 6, unitPrice: 2000, taxRate: 18, amount: 12000 },
    ],
  },
  {
    id: 3,
    quotation_number: 'QUO-2024-0040',
    customer_name: 'Pooja Iyer (Kakkanad Villa)',
    customer_email: 'pooja.iyer@gmail.com',
    customer_phone: '+91 96789 12345',
    quotation_date: 'May 26, 2024',
    valid_until: 'Jun 10, 2024',
    amount: 18000,
    subtotal: 16000,
    tax_amount: 2880,
    discount_amount: 880,
    status: 'converted',
    converted_invoice_id: 'INV-2024-0186',
    terms: 'Payment converted to Invoice INV-2024-0186. Standard villa maintenance terms apply.',
    notes: 'Customer accepted quote via WhatsApp and invoice was generated.',
    items: [
      { description: 'Annual Maintenance Contract - 5 Residential AC Units', qty: 1, unitPrice: 16000, taxRate: 18, amount: 16000 },
    ],
  },
  {
    id: 4,
    quotation_number: 'QUO-2024-0039',
    customer_name: 'CyberPark Tech Space',
    customer_email: 'admin@cyberpark.kerala.gov.in',
    customer_phone: '+91 89432 10987',
    quotation_date: 'May 20, 2024',
    valid_until: 'Jun 04, 2024',
    amount: 115000,
    subtotal: 105000,
    tax_amount: 18900,
    discount_amount: 8900,
    status: 'viewed',
    converted_invoice_id: '',
    terms: 'Quotation viewed by client procurement portal. Valid for government procurement rules.',
    notes: 'Server room precision AC maintenance & backup condenser installation.',
    items: [
      { description: 'Precision Air Conditioner (PAC) Emergency Maintenance', qty: 3, unitPrice: 25000, taxRate: 18, amount: 75000 },
      { description: 'Thermal Imaging & Energy Efficiency Audit', qty: 1, unitPrice: 30000, taxRate: 18, amount: 30000 },
    ],
  },
  {
    id: 5,
    quotation_number: 'QUO-2024-0038',
    customer_name: 'Hilite Residency Flat Owners',
    customer_email: 'residents@hiliteresidency.com',
    customer_phone: '+91 94470 54321',
    quotation_date: 'May 10, 2024',
    valid_until: 'May 25, 2024',
    amount: 42000,
    subtotal: 38000,
    tax_amount: 6840,
    discount_amount: 2840,
    status: 'expired',
    converted_invoice_id: '',
    terms: 'Special bulk resident discount was valid until May 25, 2024.',
    notes: 'Quotation expired. Needs requoting if client requests renewed pricing.',
    items: [
      { description: 'Bulk Pre-Monsoon AC Servicing Package (12 Apartments)', qty: 12, unitPrice: 3166.66, taxRate: 18, amount: 38000 },
    ],
  },
  {
    id: 6,
    quotation_number: 'QUO-2024-0037',
    customer_name: 'Zayan Malik',
    customer_email: 'zayan@coolfix-store.com',
    customer_phone: '+91 98460 99887',
    quotation_date: 'May 05, 2024',
    valid_until: 'May 20, 2024',
    amount: 9500,
    subtotal: 8500,
    tax_amount: 1530,
    discount_amount: 530,
    status: 'draft',
    converted_invoice_id: '',
    terms: 'Draft proposal for sensor board replacement and general check-up.',
    notes: 'Pending review before dispatching to client.',
    items: [
      { description: 'Inverter AC Sensor Board & PCB Testing', qty: 1, unitPrice: 5500, taxRate: 18, amount: 5500 },
      { description: 'Full System Labor & Outdoor Unit Cleaning', qty: 1, unitPrice: 3000, taxRate: 18, amount: 3000 },
    ],
  },
];

export const INITIAL_ACCOUNTS: PaymentAccount[] = [
  { id: 1, name: 'Qiyam Business Current A/c', account_number: '50200012345678', account_type: 'Bank Account', provider: 'Federal Bank', current_balance: 2478350.0, status: 'Active' },
  { id: 2, name: 'HDFC Business Account', account_number: '50100234567890', account_type: 'Bank Account', provider: 'HDFC Bank', current_balance: 1245600.0, status: 'Active' },
  { id: 3, name: 'Axis Current Account', account_number: '917020123456789', account_type: 'Bank Account', provider: 'Axis Bank', current_balance: 838400.0, status: 'Active' },
  { id: 4, name: 'Razorpay Online Payments', account_number: 'rzp_a1b2c3d4e5f6', account_type: 'Payment Gateway', provider: 'Razorpay', current_balance: 350000.0, status: 'Active' },
  { id: 5, name: 'PayPal Business', account_number: 'paypal.me/qiyambs', account_type: 'Payment Gateway', provider: 'PayPal', current_balance: 525200.0, status: 'Active' },
  { id: 6, name: 'Head Office Cash', account_number: '', account_type: 'Cash Account', provider: 'Cash in Hand', current_balance: 125600.0, status: 'Active' },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 1,
    title: 'AC Compressor Gas Charging & Leak Inspection',
    subtitle: 'Field verification for 2.0 Ton Inverter split system',
    related_to: 'JOB-1024',
    assignee: 'Amit Sharma',
    priority: 'high',
    status: 'in_progress',
    due_date: 'Today 5:00 PM',
    tags: ['QC', 'HVAC', 'Operations'],
    description: 'Perform full pressure check, vacuum cycle, and refrigerant refill.',
    checklist: [
      { id: 'c1', text: 'Pre-check refrigerant pressure & vacuum holding', completed: true },
      { id: 'c2', text: 'Compressor running amp & voltage measurement', completed: true },
      { id: 'c3', text: 'Customer digital signoff & billing confirmation', completed: false },
    ],
  },
  {
    id: 2,
    title: 'Precision Server Room AC Preventive Maintenance',
    subtitle: 'Quarterly compliance and thermal airflow audit',
    related_to: 'JOB-1025',
    assignee: 'Arjun Nair',
    priority: 'high',
    status: 'in_progress',
    due_date: 'Today 6:30 PM',
    tags: ['PAC', 'DataCenter', 'Compliance'],
    description: 'Ensure continuous cooling redundancy for primary server rack.',
    checklist: [
      { id: 'c4', text: 'Inspect dual condenser fans & blower bearing lubrication', completed: true },
      { id: 'c5', text: 'Test automatic switchover to secondary standby unit', completed: false },
      { id: 'c6', text: 'Calibrate digital temperature & humidity sensor probes', completed: false },
    ],
  },
  {
    id: 3,
    title: 'Duct Cleaning & Microbial Sanitization Handover',
    subtitle: 'Multi-story office ductwork disinfection procedure',
    related_to: 'JOB-1026',
    assignee: 'Rahul Singh',
    priority: 'medium',
    status: 'pending',
    due_date: 'Tomorrow 11:00 AM',
    tags: ['Sanitization', 'Ductwork'],
    description: 'Thorough vacuum decontamination and antimicrobial misting.',
    checklist: [
      { id: 'c7', text: 'Seal all supply and return ceiling diffusers', completed: false },
      { id: 'c8', text: 'Deploy high-velocity rotary brush and negative air vacuum', completed: false },
      { id: 'c9', text: 'Conduct post-clean particulate matter laser audit', completed: false },
    ],
  },
  {
    id: 4,
    title: 'Emergency Inverter PCB Board Replacement & Test Run',
    subtitle: 'Burned controller repair completed with warranty seal',
    related_to: 'JOB-1027',
    assignee: 'Amit Sharma',
    priority: 'high',
    status: 'completed',
    due_date: 'Yesterday 4:00 PM',
    tags: ['Repair', 'Electrical'],
    description: 'Emergency board swap done and verified with 45-minute continuous run.',
    checklist: [
      { id: 'c10', text: 'Isolate 230V mains and discharge filter capacitor', completed: true },
      { id: 'c11', text: 'Install genuine Daikin replacement inverter PCB', completed: true },
      { id: 'c12', text: 'Run 45-minute stress cycle and verify delta-T cooling', completed: true },
      { id: 'c13', text: 'Customer signed warranty sheet & invoice collected', completed: true },
    ],
  },
];
