# Generated by Django 5.0.14 on 2026-09-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_str', models.CharField(default='May 31, 2024', max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(default='Rent & Utilities', max_length=100)),
                ('vendor', models.CharField(default='Landlord', max_length=150)),
                ('amount', models.FloatField(default=55000.0)),
                ('payment_mode', models.CharField(default='Bank Transfer', max_length=50)),
                ('project', models.CharField(blank=True, default='-', max_length=100)),
                ('status', models.CharField(default='paid', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default='INV-2024-0186', max_length=50)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(default='acservices@gmail.com', max_length=254)),
                ('customer_phone', models.CharField(blank=True, default='+91 98765 43210', max_length=50)),
                ('invoice_date', models.CharField(default='May 31, 2024', max_length=50)),
                ('due_date', models.CharField(default='Jun 14, 2024', max_length=50)),
                ('amount', models.FloatField(default=12500.0)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('partial_paid', 'Partially Paid'), ('overdue', 'Overdue'), ('sent', 'Sent'), ('draft', 'Draft'), ('cancelled', 'Cancelled')], default='paid', max_length=50)),
                ('paid_amount', models.FloatField(default=12500.0)),
                ('payment_method', models.CharField(default='UPI', max_length=50)),
                ('payment_date', models.CharField(default='May 31, 2024', max_length=50)),
                ('items', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('account_type', models.CharField(default='Bank Account', max_length=50)),
                ('provider', models.CharField(default='HDFC Bank', max_length=100)),
                ('current_balance', models.FloatField(default=1245600.0)),
                ('status', models.CharField(default='Active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_str', models.CharField(default='May 31, 2024', max_length=50)),
                ('tx_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer'), ('refund', 'Refund')], default='income', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(default='AC Services', max_length=100)),
                ('party', models.CharField(default='Amit Sharma', max_length=150)),
                ('account', models.CharField(default='HDFC Bank - 1234', max_length=100)),
                ('amount', models.FloatField(default=12500.0)),
                ('payment_mode', models.CharField(default='UPI', max_length=50)),
                ('reference_id', models.CharField(default='INV-2024-0521', max_length=100)),
                ('status', models.CharField(default='completed', max_length=50)),
            ],
        ),
    ]
