# Generated by Django 5.0.14 on 2026-09-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(default='QUO-2024-0042', max_length=50)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('customer_phone', models.CharField(blank=True, default='+91 98765 43210', max_length=50)),
                ('quotation_date', models.CharField(default='May 30, 2024', max_length=50)),
                ('valid_until', models.CharField(default='Jun 15, 2024', max_length=50)),
                ('amount', models.FloatField(default=0.0)),
                ('subtotal', models.FloatField(default=0.0)),
                ('tax_amount', models.FloatField(default=0.0)),
                ('discount_amount', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('converted', 'Converted to Invoice')], default='draft', max_length=50)),
                ('converted_invoice_id', models.CharField(blank=True, default='', max_length=50)),
                ('terms', models.TextField(blank=True, default='Validity: 15 days. 50% advance required upon acceptance.')),
                ('notes', models.TextField(blank=True, default='')),
                ('items', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
