# Generated by Django 5.0.14 on 2026-09-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='customer_gstin',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tax_rate',
            field=models.FloatField(default=18.0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tax_type',
            field=models.CharField(default='intra_state', max_length=50),
        ),
    ]
