import React, { useState } from 'react';
import {
  Users, FileText, Receipt, Landmark, BarChart3, Download,
  MoreVertical, Calendar, Filter, Plus, CheckCircle2,
  Clock, ShieldCheck, Zap, Building2, UserCheck, ArrowRight,
  TrendingUp, Search, Eye, Sparkles, ChevronRight, X
} from 'lucide-react';
import { PayrollReportItem, PayrollSubView } from '@/types';
import { PeoplePowerProgressBadge } from './PeoplePowerProgressBadge';

interface Props {
  reports: PayrollReportItem[];
  onNavigate: (view: PayrollSubView) => void;
  onGenerateReport?: (report: PayrollReportItem) => void;
}

export const PayrollReportsView: React.FC<Props> = ({
  reports: initialReports,
  onNavigate,
  onGenerateReport,
}) => {
  const [reportsList, setReportsList] = useState<PayrollReportItem[]>(initialReports);
  const [trendRange, setTrendRange] = useState<'Last 6 Months' | 'Last 3 Months' | 'Last 12 Months'>('Last 6 Months');
  const [selectedMonth, setSelectedMonth] = useState('May 2024');
  const [selectedDepartment, setSelectedDepartment] = useState('All Departments');
  const [selectedEmployee, setSelectedEmployee] = useState('All Employees');
  const [selectedReportType, setSelectedReportType] = useState('All Report Types');
  const [searchQuery, setSearchQuery] = useState('');
  const [activeMenuId, setActiveMenuId] = useState<string | number | null>(null);
  const [hoveredSlice, setHoveredSlice] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [notification, setNotification] = useState<string | null>(null);
  const [customReportModalOpen, setCustomReportModalOpen] = useState(false);
  const [previewReport, setPreviewReport] = useState<PayrollReportItem | null>(null);

  // Scheduled reports state
  const [scheduledReports, setScheduledReports] = useState([
    { id: 1, name: 'Monthly Payroll Summary', schedule: '1st of every month', active: true },
    { id: 2, name: 'Statutory Compliance Report', schedule: '5th of every month', active: true },
    { id: 3, name: 'Department-wise Payroll', schedule: '10th of every month', active: true },
  ]);

  // Trend data points
  const trendData = [
    { month: 'Jan', gross: 1400000, deductions: 280000, net: 1120000 },
    { month: 'Feb', gross: 1720000, deductions: 350000, net: 1370000 },
    { month: 'Mar', gross: 1580000, deductions: 310000, net: 1270000 },
    { month: 'Apr', gross: 1620000, deductions: 320000, net: 1300000 },
    { month: 'May', gross: 1780000, deductions: 360000, net: 1420000 },
  ];

  // Cost Distribution Donut Slices
  const distributionSlices = [
    { label: 'Basic Salary', amount: 425000, percent: 40.0, color: '#3B82F6' },
    { label: 'HRA', amount: 170000, percent: 16.0, color: '#06B6D4' },
    { label: 'Allowances', amount: 125000, percent: 11.8, color: '#F97316' },
    { label: 'Incentives', amount: 90000, percent: 8.5, color: '#F59E0B' },
    { label: 'Employer PF', amount: 62300, percent: 5.9, color: '#10B981' },
    { label: 'Employee Deductions', amount: 100200, percent: 9.4, color: '#8B5CF6' },
    { label: 'Others', amount: 89000, percent: 8.4, color: '#64748B' },
  ];

  const quickReportsList = [
    { title: 'Payroll Summary', icon: FileText, color: 'text-blue-600 bg-blue-50' },
    { title: 'Employee Salary Report', icon: UserCheck, color: 'text-emerald-600 bg-emerald-50' },
    { title: 'Department-wise Payroll', icon: Building2, color: 'text-amber-600 bg-amber-50' },
    { title: 'Deductions Report', icon: Clock, color: 'text-rose-600 bg-rose-50' },
    { title: 'Statutory Compliance Report', icon: ShieldCheck, color: 'text-indigo-600 bg-indigo-50' },
    { title: 'Reimbursement Report', icon: Receipt, color: 'text-pink-600 bg-pink-50' },
    { title: 'Off-cycle Payroll Report', icon: Zap, color: 'text-yellow-600 bg-yellow-50' },
    { title: 'Year-wise Comparison', icon: BarChart3, color: 'text-purple-600 bg-purple-50' },
  ];

  const showToast = (msg: string) => {
    setNotification(msg);
    setTimeout(() => setNotification(null), 3500);
  };

  const handleDownload = (report: PayrollReportItem) => {
    // Generate real CSV download
    const csvContent =
      `Report Name: ${report.name}\r\n` +
      `Period: ${report.period}\r\n` +
      `Generated On: ${report.generated_on}\r\n` +
      `Generated By: ${report.generated_by}\r\n` +
      `Status: ${report.status}\r\n\r\n` +
      `Employee ID,Employee Name,Department,Gross Salary,Total Deductions,Net Salary,Payment Status\r\n` +
      `EMP001,Amit Sharma,Operations,₹42000,₹6500,₹35500,Paid\r\n` +
      `EMP002,Rahul Singh,Sales,₹36000,₹5500,₹30500,Paid\r\n` +
      `EMP003,Priya Mehta,Marketing,₹48000,₹8000,₹40000,Paid\r\n` +
      `EMP004,Vikram Kumar,Technology,₹52000,₹6000,₹46000,Paid\r\n` +
      `EMP005,Nazia A,HR,₹40500,₹5000,₹35500,Paid\r\n` +
      `EMP006,Sameer K,Finance,₹55000,₹7000,₹48000,Paid\r\n`;

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `${report.name.toLowerCase().replace(/\s+/g, '_')}_${report.period.replace(/\s+/g, '_')}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    showToast(`Downloaded ${report.name} successfully!`);
  };

  const handleGenerate = (reportName?: string) => {
    setIsGenerating(true);
    setTimeout(() => {
      const name = reportName || (selectedReportType !== 'All Report Types' ? selectedReportType : 'Payroll Summary');
      const newReport: PayrollReportItem = {
        id: Date.now(),
        name: name,
        type: name.includes('Salary') ? 'Employee-wise' : name.includes('Deductions') ? 'Deductions' : name.includes('Compliance') ? 'Compliance' : 'Summary',
        period: selectedMonth,
        generated_on: new Date().toLocaleString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit', hour12: true }),
        generated_by: 'Faris Usman',
        status: 'Completed',
      };
      const updated = [newReport, ...reportsList];
      setReportsList(updated);
      setIsGenerating(false);
      showToast(`Generated ${newReport.name} for ${newReport.period}!`);
      if (onGenerateReport) onGenerateReport(newReport);
    }, 600);
  };

  const filteredReports = reportsList.filter((r) => {
    const matchesSearch = r.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      r.generated_by.toLowerCase().includes(searchQuery.toLowerCase()) ||
      r.period.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesType = selectedReportType === 'All Report Types' || r.name.toLowerCase().includes(selectedReportType.toLowerCase()) || r.type.toLowerCase().includes(selectedReportType.toLowerCase());
    return matchesSearch && matchesType;
  });

  // Calculate SVG arc paths for Donut chart
  let cumulativeAngle = 0;
  const donutPaths = distributionSlices.map((slice) => {
    const angle = (slice.percent / 100) * 360;
    const startAngle = cumulativeAngle;
    const endAngle = cumulativeAngle + angle;
    cumulativeAngle += angle;

    const radStart = ((startAngle - 90) * Math.PI) / 180.0;
    const radEnd = ((endAngle - 90) * Math.PI) / 180.0;

    const cx = 100;
    const cy = 100;
    const rOuter = 85;
    const rInner = 55;

    const x1 = cx + rOuter * Math.cos(radStart);
    const y1 = cy + rOuter * Math.sin(radStart);
    const x2 = cx + rOuter * Math.cos(radEnd);
    const y2 = cy + rOuter * Math.sin(radEnd);

    const x3 = cx + rInner * Math.cos(radEnd);
    const y3 = cy + rInner * Math.sin(radEnd);
    const x4 = cx + rInner * Math.cos(radStart);
    const y4 = cy + rInner * Math.sin(radStart);

    const largeArc = angle > 180 ? 1 : 0;
    const d = `M ${x1} ${y1} A ${rOuter} ${rOuter} 0 ${largeArc} 1 ${x2} ${y2} L ${x3} ${y3} A ${rInner} ${rInner} 0 ${largeArc} 0 ${x4} ${y4} Z`;

    return {
      ...slice,
      d,
    };
  });

  return (
    <div className="space-y-6">
      {/* Toast Notification */}
      {notification && (
        <div className="fixed bottom-6 right-6 z-50 bg-slate-900 text-white text-xs font-semibold px-4 py-2.5 rounded-xl shadow-xl flex items-center gap-2 animate-in fade-in slide-in-from-bottom-2">
          <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
          <span>{notification}</span>
        </div>
      )}

      {/* Top Banner Card (Screenshot 8 / Qiyam OS pattern) */}
      <div className="relative overflow-hidden rounded-2xl bg-gradient-to-r from-emerald-50/70 via-teal-50/40 to-slate-50 border border-emerald-100/80 p-5 sm:p-6 flex flex-col md:flex-row items-start md:items-center justify-between gap-4 shadow-2xs">
        <div className="space-y-1.5 max-w-xl">
          <div className="flex items-center gap-2">
            <span className="text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full bg-emerald-600/10 text-emerald-700">
              Analytics & Cost Intelligence
            </span>
          </div>
          <h2 className="text-xl sm:text-2xl font-black text-slate-900 tracking-tight">Payroll Reports</h2>
          <p className="text-xs sm:text-sm text-slate-600 font-medium">
            Analyze gross expense trends, department cost allocations, tax withholdings, and export statements.
          </p>
        </div>

        <div className="flex items-center gap-3 shrink-0">
          <PeoplePowerProgressBadge />
          <div className="hidden sm:flex items-center gap-3 bg-white/90 backdrop-blur-xs px-4 py-3 rounded-2xl border border-white/60 shadow-2xs">
            <div>
              <h4 className="text-xs font-bold text-slate-900">Turn Payroll Data into Decisions</h4>
              <p className="text-[11px] text-slate-500">Live analytics for workforce planning and audit compliance.</p>
            </div>
            <div className="w-10 h-10 rounded-xl bg-emerald-600 text-white flex items-center justify-center font-bold text-base shadow-sm shadow-emerald-600/20">
              <BarChart3 className="w-5 h-5" />
            </div>
          </div>
        </div>
      </div>

      {/* Top 4 KPI Metric Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* Total Payroll Cost */}
        <div className="bg-white rounded-2xl border border-slate-200/90 p-5 shadow-2xs hover:shadow-sm transition-all duration-200">
          <div className="flex items-center justify-between">
            <div className="w-10 h-10 rounded-xl bg-blue-50 border border-blue-100 flex items-center justify-center text-blue-600">
              <Users className="w-5 h-5" />
            </div>
            <span className="inline-flex items-center gap-1 text-[11px] font-bold text-emerald-600 bg-emerald-50 border border-emerald-100 px-2 py-0.5 rounded-full">
              <TrendingUp className="w-3 h-3" />
              8% from last month
            </span>
          </div>
          <div className="mt-4">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">Total Payroll Cost</span>
            <div className="text-2xl font-black text-slate-900 tracking-tight mt-0.5 font-mono">₹10,62,500</div>
          </div>
        </div>

        {/* Total Deductions */}
        <div className="bg-white rounded-2xl border border-slate-200/90 p-5 shadow-2xs hover:shadow-sm transition-all duration-200">
          <div className="flex items-center justify-between">
            <div className="w-10 h-10 rounded-xl bg-rose-50 border border-rose-100 flex items-center justify-center text-rose-600">
              <FileText className="w-5 h-5" />
            </div>
            <span className="inline-flex items-center gap-1 text-[11px] font-bold text-emerald-600 bg-emerald-50 border border-emerald-100 px-2 py-0.5 rounded-full">
              <TrendingUp className="w-3 h-3" />
              6% from last month
            </span>
          </div>
          <div className="mt-4">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">Total Deductions</span>
            <div className="text-2xl font-black text-slate-900 tracking-tight mt-0.5 font-mono">₹1,82,500</div>
          </div>
        </div>

        {/* Net Payroll */}
        <div className="bg-white rounded-2xl border border-slate-200/90 p-5 shadow-2xs hover:shadow-sm transition-all duration-200">
          <div className="flex items-center justify-between">
            <div className="w-10 h-10 rounded-xl bg-purple-50 border border-purple-100 flex items-center justify-center text-purple-600">
              <Landmark className="w-5 h-5" />
            </div>
            <span className="inline-flex items-center gap-1 text-[11px] font-bold text-emerald-600 bg-emerald-50 border border-emerald-100 px-2 py-0.5 rounded-full">
              <TrendingUp className="w-3 h-3" />
              9% from last month
            </span>
          </div>
          <div className="mt-4">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">Net Payroll</span>
            <div className="text-2xl font-black text-slate-900 tracking-tight mt-0.5 font-mono">₹8,80,000</div>
          </div>
        </div>

        {/* Total Employees */}
        <div className="bg-white rounded-2xl border border-slate-200/90 p-5 shadow-2xs hover:shadow-sm transition-all duration-200">
          <div className="flex items-center justify-between">
            <div className="w-10 h-10 rounded-xl bg-amber-50 border border-amber-100 flex items-center justify-center text-amber-600">
              <UserCheck className="w-5 h-5" />
            </div>
            <span className="text-xs font-semibold text-slate-400">Active Employees</span>
          </div>
          <div className="mt-4">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">Total Employees</span>
            <div className="text-2xl font-black text-slate-900 tracking-tight mt-0.5 font-mono">32</div>
          </div>
        </div>
      </div>

      {/* Middle Row: Trend Chart & Cost Distribution Donut */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Payroll Expense Trend */}
        <div className="lg:col-span-7 bg-white rounded-2xl border border-slate-200/90 p-6 shadow-2xs">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 mb-6">
            <div>
              <h3 className="text-base font-bold text-slate-900">Payroll Expense Trend</h3>
              <p className="text-xs text-slate-500">Gross vs Deductions vs Net payout</p>
            </div>
            <div className="flex items-center gap-3">
              <div className="flex items-center gap-2 text-xs font-medium text-slate-600">
                <span className="inline-flex items-center gap-1.5"><span className="w-2.5 h-2.5 rounded-sm bg-blue-500" /> Gross Payroll</span>
                <span className="inline-flex items-center gap-1.5"><span className="w-2.5 h-2.5 rounded-sm bg-pink-400" /> Deductions</span>
                <span className="inline-flex items-center gap-1.5"><span className="w-2.5 h-2.5 rounded-full bg-emerald-500" /> Net Payroll</span>
              </div>
              <select
                value={trendRange}
                onChange={(e) => setTrendRange(e.target.value as any)}
                className="text-xs font-bold bg-slate-50 border border-slate-200 rounded-xl px-2.5 py-1.5 text-slate-700 outline-none focus:ring-2 focus:ring-blue-500/20"
              >
                <option value="Last 6 Months">Last 6 Months</option>
                <option value="Last 3 Months">Last 3 Months</option>
                <option value="Last 12 Months">Last 12 Months</option>
              </select>
            </div>
          </div>

          {/* SVG Bar & Line Combo Chart */}
          <div className="relative h-64 w-full">
            <svg viewBox="0 0 500 220" className="w-full h-full overflow-visible">
              {/* Y Axis Grid lines */}
              {[
                { label: '₹20L', y: 20 },
                { label: '₹15L', y: 65 },
                { label: '₹10L', y: 110 },
                { label: '₹5L', y: 155 },
                { label: '₹ 0', y: 200 },
              ].map((grid, idx) => (
                <g key={idx}>
                  <text x="5" y={grid.y + 4} fill="#94A3B8" fontSize="10" fontWeight="500">
                    {grid.label}
                  </text>
                  <line x1="45" y1={grid.y} x2="490" y2={grid.y} stroke="#F1F5F9" strokeDasharray="3 3" />
                </g>
              ))}

              {/* Bars & Lines */}
              {trendData.map((d, idx) => {
                const xBase = 75 + idx * 85;
                // Scale ₹20L = 2000000 -> 180 height
                const hGross = (d.gross / 2000000) * 180;
                const hDed = (d.deductions / 2000000) * 180;
                const yNet = 200 - (d.net / 2000000) * 180;

                return (
                  <g key={d.month} className="group cursor-pointer">
                    {/* Gross Bar */}
                    <rect
                      x={xBase - 16}
                      y={200 - hGross}
                      width="14"
                      height={hGross}
                      rx="3"
                      fill="#3B82F6"
                      className="transition-all duration-200 group-hover:fill-blue-600"
                    />
                    {/* Deductions Bar */}
                    <rect
                      x={xBase + 2}
                      y={200 - hDed}
                      width="14"
                      height={hDed}
                      rx="3"
                      fill="#F472B6"
                      className="transition-all duration-200 group-hover:fill-pink-500"
                    />
                    {/* Month Label */}
                    <text x={xBase} y="215" textAnchor="middle" fill="#64748B" fontSize="11" fontWeight="600">
                      {d.month}
                    </text>
                  </g>
                );
              })}

              {/* Net Payroll Line connecting dots */}
              <polyline
                fill="none"
                stroke="#10B981"
                strokeWidth="2.5"
                points={trendData.map((d, idx) => `${75 + idx * 85},${200 - (d.net / 2000000) * 180}`).join(' ')}
              />

              {/* Net Payroll points */}
              {trendData.map((d, idx) => {
                const cx = 75 + idx * 85;
                const cy = 200 - (d.net / 2000000) * 180;
                return (
                  <g key={idx} className="group/dot cursor-pointer">
                    <circle cx={cx} cy={cy} r="4.5" fill="#10B981" stroke="#FFFFFF" strokeWidth="2" />
                    {/* Tooltip on hover */}
                    <title>{`${d.month}: Net ₹${(d.net / 100000).toFixed(2)}L | Gross ₹${(d.gross / 100000).toFixed(2)}L`}</title>
                  </g>
                );
              })}
            </svg>
          </div>
        </div>

        {/* Payroll Cost Distribution (May 2024) */}
        <div className="lg:col-span-5 bg-white rounded-2xl border border-slate-200/90 p-6 shadow-2xs flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-base font-bold text-slate-900">Payroll Cost Distribution (May 2024)</h3>
            </div>

            <div className="flex flex-col sm:flex-row items-center gap-6">
              {/* Donut Chart */}
              <div className="relative w-44 h-44 shrink-0 flex items-center justify-center">
                <svg viewBox="0 0 200 200" className="w-full h-full transform -rotate-90">
                  {donutPaths.map((slice, idx) => (
                    <path
                      key={idx}
                      d={slice.d}
                      fill={slice.color}
                      className="transition-all duration-200 cursor-pointer hover:opacity-80"
                      onMouseEnter={() => setHoveredSlice(slice.label)}
                      onMouseLeave={() => setHoveredSlice(null)}
                    />
                  ))}
                </svg>
                {/* Center text */}
                <div className="absolute inset-0 flex flex-col items-center justify-center text-center pointer-events-none">
                  <span className="text-sm font-black text-slate-900 font-mono">₹10,62,500</span>
                  <span className="text-[10px] font-bold text-slate-400 uppercase tracking-tight">Total Payroll Cost</span>
                </div>
              </div>

              {/* Legend List */}
              <div className="space-y-1.5 w-full">
                {distributionSlices.map((slice) => {
                  const isHovered = hoveredSlice === slice.label;
                  return (
                    <div
                      key={slice.label}
                      onMouseEnter={() => setHoveredSlice(slice.label)}
                      onMouseLeave={() => setHoveredSlice(null)}
                      className={`flex items-center justify-between py-1 px-2 rounded-lg transition-all text-xs ${
                        isHovered ? 'bg-slate-100/90 font-bold' : ''
                      }`}
                    >
                      <div className="flex items-center gap-2 truncate">
                        <span className="w-2.5 h-2.5 rounded-full shrink-0" style={{ backgroundColor: slice.color }} />
                        <span className="text-slate-700 truncate">{slice.label}</span>
                      </div>
                      <div className="flex items-center gap-2 shrink-0">
                        <span className="font-mono text-slate-900 font-semibold">₹{slice.amount.toLocaleString('en-IN')}</span>
                        <span className="text-[11px] text-slate-400">({slice.percent.toFixed(1)}%)</span>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>

          <div className="mt-4 pt-3 border-t border-slate-100 flex items-center justify-between text-xs text-slate-500">
            <span>Calculated from 32 active employee CTCs</span>
            <button
              onClick={() => onNavigate('manage-salary')}
              className="text-blue-600 hover:text-blue-700 font-bold flex items-center gap-1"
            >
              Configure CTC <ChevronRight className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
      </div>

      {/* Filter & Generation Bar */}
      <div className="bg-white rounded-2xl border border-slate-200/90 p-4 shadow-2xs flex flex-wrap items-center gap-3">
        {/* Month Selector */}
        <div className="flex items-center gap-2 bg-slate-50 border border-slate-200/90 rounded-xl px-3 py-2 text-xs font-semibold text-slate-700">
          <Calendar className="w-4 h-4 text-slate-400 shrink-0" />
          <select
            value={selectedMonth}
            onChange={(e) => setSelectedMonth(e.target.value)}
            className="bg-transparent outline-none cursor-pointer pr-2"
          >
            <option value="May 2024">May 2024</option>
            <option value="Apr 2024">Apr 2024</option>
            <option value="Mar 2024">Mar 2024</option>
            <option value="Feb 2024">Feb 2024</option>
            <option value="Jan 2024">Jan 2024</option>
          </select>
        </div>

        {/* Department Selector */}
        <div className="flex items-center gap-2 bg-slate-50 border border-slate-200/90 rounded-xl px-3 py-2 text-xs font-semibold text-slate-700">
          <Filter className="w-4 h-4 text-slate-400 shrink-0" />
          <select
            value={selectedDepartment}
            onChange={(e) => setSelectedDepartment(e.target.value)}
            className="bg-transparent outline-none cursor-pointer pr-2"
          >
            <option value="All Departments">All Departments</option>
            <option value="Operations">Operations</option>
            <option value="Sales">Sales</option>
            <option value="Marketing">Marketing</option>
            <option value="Technology">Technology</option>
            <option value="HR">HR</option>
            <option value="Finance">Finance</option>
          </select>
        </div>

        {/* Employee Selector */}
        <div className="flex items-center gap-2 bg-slate-50 border border-slate-200/90 rounded-xl px-3 py-2 text-xs font-semibold text-slate-700">
          <UserCheck className="w-4 h-4 text-slate-400 shrink-0" />
          <select
            value={selectedEmployee}
            onChange={(e) => setSelectedEmployee(e.target.value)}
            className="bg-transparent outline-none cursor-pointer pr-2"
          >
            <option value="All Employees">All Employees</option>
            <option value="Amit Sharma">Amit Sharma</option>
            <option value="Rahul Singh">Rahul Singh</option>
            <option value="Priya Mehta">Priya Mehta</option>
            <option value="Vikram Kumar">Vikram Kumar</option>
            <option value="Nazia A">Nazia A</option>
          </select>
        </div>

        {/* Report Type Selector */}
        <div className="flex items-center gap-2 bg-slate-50 border border-slate-200/90 rounded-xl px-3 py-2 text-xs font-semibold text-slate-700">
          <FileText className="w-4 h-4 text-slate-400 shrink-0" />
          <select
            value={selectedReportType}
            onChange={(e) => setSelectedReportType(e.target.value)}
            className="bg-transparent outline-none cursor-pointer pr-2"
          >
            <option value="All Report Types">All Report Types</option>
            <option value="Payroll Summary">Payroll Summary</option>
            <option value="Employee Salary Report">Employee Salary Report</option>
            <option value="Deductions Report">Deductions Report</option>
            <option value="Compliance Report">Compliance Report</option>
            <option value="Reimbursement Report">Reimbursement Report</option>
          </select>
        </div>

        {/* Generate Report Button */}
        <div className="ml-auto">
          <button
            onClick={() => handleGenerate()}
            disabled={isGenerating}
            className="flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white font-bold px-5 py-2.5 rounded-xl shadow-xs transition-all active:scale-[0.98] disabled:opacity-50 text-xs cursor-pointer"
          >
            <BarChart3 className="w-4 h-4" />
            <span>{isGenerating ? 'Generating...' : 'Generate Report'}</span>
          </button>
        </div>
      </div>

      {/* Main Content Grid: Recent Reports & Right Sidebars */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column (8 cols): Recent Reports */}
        <div className="lg:col-span-8 bg-white rounded-2xl border border-slate-200/90 p-6 shadow-2xs">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-4">
            <div>
              <h3 className="text-base font-bold text-slate-900">Recent Reports</h3>
              <p className="text-xs text-slate-500">View and download recent payroll statements</p>
            </div>
            <div className="flex items-center gap-3 w-full sm:w-auto">
              <div className="relative w-full sm:w-48">
                <Search className="w-3.5 h-3.5 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
                <input
                  type="text"
                  placeholder="Search reports..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="w-full pl-8 pr-3 py-1.5 text-xs bg-slate-50 border border-slate-200 rounded-xl outline-none focus:ring-2 focus:ring-blue-500/20"
                />
              </div>
              <button
                onClick={() => setSearchQuery('')}
                className="text-xs font-bold text-blue-600 hover:text-blue-700 shrink-0"
              >
                View All
              </button>
            </div>
          </div>

          {/* Table */}
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="border-b border-slate-100 text-[11px] font-bold text-slate-400 uppercase tracking-wider">
                  <th className="py-3 px-3">#</th>
                  <th className="py-3 px-3">Report Name</th>
                  <th className="py-3 px-3">Type</th>
                  <th className="py-3 px-3">Period</th>
                  <th className="py-3 px-3">Generated On</th>
                  <th className="py-3 px-3">Generated By</th>
                  <th className="py-3 px-3">Status</th>
                  <th className="py-3 px-3 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-50 text-xs">
                {filteredReports.map((report, idx) => (
                  <tr key={report.id} className="hover:bg-slate-50/80 transition-colors group">
                    <td className="py-3.5 px-3 text-slate-400 font-semibold">{idx + 1}</td>
                    <td className="py-3.5 px-3">
                      <div className="font-bold text-slate-900 flex items-center gap-2">
                        <FileText className="w-3.5 h-3.5 text-blue-600 shrink-0" />
                        <span>{report.name}</span>
                      </div>
                    </td>
                    <td className="py-3.5 px-3 text-slate-600 font-medium">{report.type}</td>
                    <td className="py-3.5 px-3 font-medium text-slate-700">{report.period}</td>
                    <td className="py-3.5 px-3 text-slate-500 text-[11px]">{report.generated_on}</td>
                    <td className="py-3.5 px-3 font-medium text-slate-800">{report.generated_by}</td>
                    <td className="py-3.5 px-3">
                      <span className="inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-bold bg-emerald-50 text-emerald-700 border border-emerald-200">
                        {report.status}
                      </span>
                    </td>
                    <td className="py-3.5 px-3 text-right relative">
                      <div className="flex items-center justify-end gap-1.5">
                        <button
                          onClick={() => handleDownload(report)}
                          className="px-3 py-1 rounded-lg border border-slate-200 hover:border-blue-400 text-blue-600 hover:bg-blue-50 text-xs font-bold transition-all shadow-2xs"
                        >
                          Download
                        </button>
                        <div className="relative">
                          <button
                            onClick={() => setActiveMenuId(activeMenuId === report.id ? null : report.id)}
                            className="p-1 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-100"
                          >
                            <MoreVertical className="w-4 h-4" />
                          </button>

                          {activeMenuId === report.id && (
                            <div className="absolute right-0 mt-1 w-36 bg-white rounded-xl shadow-lg border border-slate-200 py-1 z-30 text-left">
                              <button
                                onClick={() => {
                                  setPreviewReport(report);
                                  setActiveMenuId(null);
                                }}
                                className="w-full px-3 py-1.5 text-xs text-slate-700 hover:bg-slate-50 flex items-center gap-2"
                              >
                                <Eye className="w-3.5 h-3.5 text-slate-400" /> Preview
                              </button>
                              <button
                                onClick={() => {
                                  handleDownload(report);
                                  setActiveMenuId(null);
                                }}
                                className="w-full px-3 py-1.5 text-xs text-slate-700 hover:bg-slate-50 flex items-center gap-2"
                              >
                                <Download className="w-3.5 h-3.5 text-slate-400" /> Export CSV
                              </button>
                              <button
                                onClick={() => {
                                  setReportsList(reportsList.filter((r) => r.id !== report.id));
                                  setActiveMenuId(null);
                                  showToast('Report deleted.');
                                }}
                                className="w-full px-3 py-1.5 text-xs text-rose-600 hover:bg-rose-50 flex items-center gap-2"
                              >
                                <X className="w-3.5 h-3.5 text-rose-500" /> Remove
                              </button>
                            </div>
                          )}
                        </div>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Right Column (4 cols): Quick Reports & Scheduled Reports */}
        <div className="lg:col-span-4 space-y-6">
          {/* Quick Reports Card */}
          <div className="bg-white rounded-2xl border border-slate-200/90 p-5 shadow-2xs">
            <div className="flex items-center justify-between mb-3">
              <h3 className="text-sm font-bold text-slate-900">Quick Reports</h3>
              <button
                onClick={() => showToast('All 8 report templates are active.')}
                className="text-xs font-bold text-blue-600 hover:text-blue-700"
              >
                View All
              </button>
            </div>

            <div className="space-y-1.5">
              {quickReportsList.map((item, idx) => {
                const IconComponent = item.icon;
                return (
                  <button
                    key={idx}
                    onClick={() => handleGenerate(item.title)}
                    className="w-full flex items-center justify-between p-2 rounded-xl hover:bg-slate-50 transition-all group text-left"
                  >
                    <div className="flex items-center gap-2.5 truncate">
                      <div className={`w-7 h-7 rounded-lg flex items-center justify-center shrink-0 ${item.color}`}>
                        <IconComponent className="w-3.5 h-3.5" />
                      </div>
                      <span className="text-xs font-bold text-slate-700 group-hover:text-blue-600 transition-colors truncate">
                        {item.title}
                      </span>
                    </div>
                    <ChevronRight className="w-4 h-4 text-slate-300 group-hover:text-blue-600 group-hover:translate-x-0.5 transition-all shrink-0" />
                  </button>
                );
              })}
            </div>
          </div>

          {/* Scheduled Reports Card */}
          <div className="bg-white rounded-2xl border border-slate-200/90 p-5 shadow-2xs">
            <div className="flex items-center justify-between mb-3">
              <h3 className="text-sm font-bold text-slate-900">Scheduled Reports</h3>
              <button
                onClick={() => setCustomReportModalOpen(true)}
                className="text-xs font-bold text-blue-600 hover:text-blue-700"
              >
                View All
              </button>
            </div>

            <div className="space-y-3">
              {scheduledReports.map((sch) => (
                <div key={sch.id} className="flex items-center justify-between p-2.5 bg-slate-50/70 border border-slate-200/80 rounded-xl">
                  <div className="space-y-0.5">
                    <p className="text-xs font-bold text-slate-900">{sch.name}</p>
                    <p className="text-[11px] text-slate-500">{sch.schedule}</p>
                  </div>
                  <span className="inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-bold bg-emerald-50 text-emerald-700 border border-emerald-200">
                    Active
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* Need Custom Reports? Card */}
          <div
            onClick={() => setCustomReportModalOpen(true)}
            className="p-4 rounded-2xl bg-gradient-to-r from-blue-500/10 via-indigo-500/10 to-sky-500/10 border border-blue-200/70 shadow-2xs hover:border-blue-400 transition-all cursor-pointer flex items-center justify-between group"
          >
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-blue-600 text-white flex items-center justify-center shadow-xs shrink-0 group-hover:scale-105 transition-transform">
                <Sparkles className="w-5 h-5" />
              </div>
              <div>
                <h4 className="text-xs font-bold text-slate-900">Need Custom Reports?</h4>
                <p className="text-[11px] text-slate-600">Create custom reports with the data you need.</p>
              </div>
            </div>
            <ChevronRight className="w-5 h-5 text-blue-600 group-hover:translate-x-1 transition-transform shrink-0" />
          </div>
        </div>
      </div>

      {/* Footer Banner */}
      <div className="bg-gradient-to-r from-blue-50/60 via-indigo-50/40 to-sky-50/60 rounded-2xl border border-blue-100 p-6 flex flex-col md:flex-row items-center justify-between gap-6 shadow-2xs">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-2xl bg-blue-600 text-white flex items-center justify-center shadow-sm shrink-0">
            <BarChart3 className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-sm sm:text-base font-bold text-slate-900">Data Today. A Stronger Tomorrow.</h3>
            <p className="text-xs text-slate-600 mt-0.5">
              Detailed payroll reports to help you stay compliant and make better business decisions.
            </p>
          </div>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 w-full md:w-auto">
          <div className="flex items-center gap-2 bg-white/80 border border-white/60 px-3 py-2 rounded-xl text-xs font-bold text-slate-700 shadow-2xs">
            <span className="w-2 h-2 rounded-full bg-blue-500" /> Accurate Insights
          </div>
          <div className="flex items-center gap-2 bg-white/80 border border-white/60 px-3 py-2 rounded-xl text-xs font-bold text-slate-700 shadow-2xs">
            <span className="w-2 h-2 rounded-full bg-emerald-500" /> Compliant Reports
          </div>
          <div className="flex items-center gap-2 bg-white/80 border border-white/60 px-3 py-2 rounded-xl text-xs font-bold text-slate-700 shadow-2xs">
            <span className="w-2 h-2 rounded-full bg-amber-500" /> Save Time
          </div>
          <div className="flex items-center gap-2 bg-white/80 border border-white/60 px-3 py-2 rounded-xl text-xs font-bold text-slate-700 shadow-2xs">
            <span className="w-2 h-2 rounded-full bg-purple-500" /> Better Decisions
          </div>
        </div>
      </div>

      {/* Custom Report Builder Modal */}
      {customReportModalOpen && (
        <div className="fixed inset-0 z-50 bg-slate-900/40 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl border border-slate-200 shadow-2xl max-w-lg w-full p-6 space-y-4 animate-in fade-in zoom-in-95">
            <div className="flex items-center justify-between border-b border-slate-100 pb-3">
              <div className="flex items-center gap-2.5">
                <div className="w-8 h-8 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center font-bold">
                  <Sparkles className="w-4 h-4" />
                </div>
                <h3 className="text-base font-bold text-slate-900">Custom Report Builder</h3>
              </div>
              <button
                onClick={() => setCustomReportModalOpen(false)}
                className="text-slate-400 hover:text-slate-600 p-1 rounded-lg"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="space-y-3 text-xs">
              <div>
                <label className="font-bold text-slate-700 block mb-1">Report Title</label>
                <input
                  type="text"
                  defaultValue="Custom Payroll Analytics"
                  className="w-full px-3 py-2 border border-slate-200 rounded-xl outline-none focus:ring-2 focus:ring-blue-500/20"
                />
              </div>

              <div>
                <label className="font-bold text-slate-700 block mb-1">Select Metric Columns</label>
                <div className="grid grid-cols-2 gap-2 mt-1">
                  {['Gross Salary', 'Total Deductions', 'Net Payout', 'TDS Withheld', 'PF (Employer/Employee)', 'ESI Contribution', 'Reimbursements', 'Attendance Days'].map((col) => (
                    <label key={col} className="flex items-center gap-2 text-slate-700 font-medium">
                      <input type="checkbox" defaultChecked className="rounded text-blue-600" />
                      <span>{col}</span>
                    </label>
                  ))}
                </div>
              </div>

              <div>
                <label className="font-bold text-slate-700 block mb-1">Export Format</label>
                <div className="flex items-center gap-4">
                  <label className="flex items-center gap-2 text-slate-700 font-medium">
                    <input type="radio" name="format" defaultChecked className="text-blue-600" />
                    <span>CSV (.csv)</span>
                  </label>
                  <label className="flex items-center gap-2 text-slate-700 font-medium">
                    <input type="radio" name="format" className="text-blue-600" />
                    <span>Excel (.xlsx)</span>
                  </label>
                  <label className="flex items-center gap-2 text-slate-700 font-medium">
                    <input type="radio" name="format" className="text-blue-600" />
                    <span>PDF (.pdf)</span>
                  </label>
                </div>
              </div>
            </div>

            <div className="flex items-center justify-end gap-3 pt-3 border-t border-slate-100">
              <button
                onClick={() => setCustomReportModalOpen(false)}
                className="px-4 py-2 rounded-xl text-slate-600 hover:bg-slate-100 font-bold text-xs"
              >
                Cancel
              </button>
              <button
                onClick={() => {
                  handleGenerate('Custom Payroll Analytics');
                  setCustomReportModalOpen(false);
                }}
                className="px-5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs shadow-xs cursor-pointer transition-all"
              >
                Generate & Save
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Preview Modal */}
      {previewReport && (
        <div className="fixed inset-0 z-50 bg-slate-900/40 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl border border-slate-200 shadow-2xl max-w-2xl w-full p-6 space-y-4 animate-in fade-in zoom-in-95">
            <div className="flex items-center justify-between border-b border-slate-100 pb-3">
              <div>
                <h3 className="text-base font-bold text-slate-900">{previewReport.name}</h3>
                <p className="text-xs text-slate-500">Period: {previewReport.period} • Generated by {previewReport.generated_by}</p>
              </div>
              <button
                onClick={() => setPreviewReport(null)}
                className="text-slate-400 hover:text-slate-600 p-1 rounded-lg"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="max-h-72 overflow-y-auto border border-slate-100 rounded-xl p-3 bg-slate-50/50 text-xs">
              <table className="w-full text-left">
                <thead>
                  <tr className="border-b border-slate-200 text-slate-500 font-bold text-[11px]">
                    <th className="pb-2">EMP ID</th>
                    <th className="pb-2">Employee</th>
                    <th className="pb-2">Gross</th>
                    <th className="pb-2">Deductions</th>
                    <th className="pb-2">Net Pay</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 text-slate-700">
                  <tr>
                    <td className="py-2 font-mono">EMP001</td>
                    <td className="py-2 font-bold">Amit Sharma</td>
                    <td className="py-2 font-mono">₹42,000</td>
                    <td className="py-2 font-mono text-rose-600">-₹6,500</td>
                    <td className="py-2 font-mono font-bold text-slate-900">₹35,500</td>
                  </tr>
                  <tr>
                    <td className="py-2 font-mono">EMP002</td>
                    <td className="py-2 font-bold">Rahul Singh</td>
                    <td className="py-2 font-mono">₹36,000</td>
                    <td className="py-2 font-mono text-rose-600">-₹5,500</td>
                    <td className="py-2 font-mono font-bold text-slate-900">₹30,500</td>
                  </tr>
                  <tr>
                    <td className="py-2 font-mono">EMP003</td>
                    <td className="py-2 font-bold">Priya Mehta</td>
                    <td className="py-2 font-mono">₹48,000</td>
                    <td className="py-2 font-mono text-rose-600">-₹8,000</td>
                    <td className="py-2 font-mono font-bold text-slate-900">₹40,000</td>
                  </tr>
                  <tr>
                    <td className="py-2 font-mono">EMP004</td>
                    <td className="py-2 font-bold">Vikram Kumar</td>
                    <td className="py-2 font-mono">₹52,000</td>
                    <td className="py-2 font-mono text-rose-600">-₹6,000</td>
                    <td className="py-2 font-mono font-bold text-slate-900">₹46,000</td>
                  </tr>
                </tbody>
              </table>
            </div>

            <div className="flex items-center justify-between pt-3 border-t border-slate-100 text-xs">
              <span className="text-slate-400">Total 32 employee records compiled.</span>
              <button
                onClick={() => {
                  handleDownload(previewReport);
                  setPreviewReport(null);
                }}
                className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-xl font-bold flex items-center gap-1.5 shadow-xs"
              >
                <Download className="w-4 h-4" /> Download Complete Report
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
