# Generated by Django 5.0.14 on 2026-09-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('branch_type', models.CharField(default='Branch Office', max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='Kerala', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('automations_count', models.IntegerField(default=0)),
                ('tasks_automated', models.IntegerField(default=0)),
                ('last_activity', models.CharField(default='Just now', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(default='connected', max_length=50)),
                ('connected_on', models.CharField(blank=True, max_length=100, null=True)),
                ('automations_enabled', models.IntegerField(default=0)),
                ('icon_slug', models.CharField(default='google', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_id', models.CharField(default='WS-10324', max_length=50, unique=True)),
                ('name', models.CharField(default='Qiyam Business OS', max_length=200)),
                ('workspace_url', models.CharField(default='qiyam-business-os.qiyamapp.com', max_length=200)),
                ('default_language', models.CharField(default='English (US)', max_length=50)),
                ('date_format', models.CharField(default='MMM DD, YYYY', max_length=50)),
                ('time_zone', models.CharField(default='(GMT+05:30) Asia/Kolkata', max_length=100)),
                ('week_starts_on', models.CharField(default='Monday', max_length=20)),
                ('enable_ai_assistant', models.BooleanField(default=True)),
                ('enable_desktop_notifications', models.BooleanField(default=True)),
                ('allow_file_uploads', models.BooleanField(default=True)),
                ('auto_save', models.BooleanField(default=True)),
                ('show_onboarding_tips', models.BooleanField(default=True)),
                ('compact_view', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(default='Faris Usman', max_length=100)),
                ('plan', models.CharField(default='Professional', max_length=50)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('members_count', models.IntegerField(default=18)),
                ('storage_used_gb', models.FloatField(default=24.6)),
                ('storage_limit_gb', models.FloatField(default=100.0)),
            ],
        ),
    ]
