# Generated by Django 5.0.14 on 2026-09-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='customers_count',
            field=models.IntegerField(default=450),
        ),
        migrations.AddField(
            model_name='branch',
            name='employees_count',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='branch',
            name='image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager_name',
            field=models.CharField(blank=True, default='Rahul Mehta', max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager_role',
            field=models.CharField(blank=True, default='Branch Manager', max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='pincode',
            field=models.CharField(blank=True, default='682016', max_length=20),
        ),
    ]
