# Generated by Django 5.0.14 on 2026-09-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_branch_customers_count_branch_employees_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, default='branch@qiyamventures.com', max_length=254),
        ),
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, default='+91 495 276 5400', max_length=50),
        ),
    ]
