# Generated by Django 5.0.14 on 2026-09-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_branch_address_branch_email_branch_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
